// !!!GENERATED FILE, DO NOT EDIT!!!
// This file is auto-generated by supabase in scripts/generate-types.ts
// Schema: public
// Generated at: 2025-11-16T08:41:59.146Z

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '13.0.5';
  };
  public: {
    Tables: {
      activities: {
        Row: {
          amount: number | null;
          babyId: string;
          createdAt: string;
          details: Json | null;
          duration: number | null;
          endTime: string | null;
          feedingSource: Database['public']['Enums']['feedingSource'] | null;
          id: string;
          isScheduled: boolean;
          notes: string | null;
          startTime: string;
          type: Database['public']['Enums']['activityType'];
          updatedAt: string;
          userId: string;
        };
        Insert: {
          amount?: number | null;
          babyId: string;
          createdAt?: string;
          details?: Json | null;
          duration?: number | null;
          endTime?: string | null;
          feedingSource?: Database['public']['Enums']['feedingSource'] | null;
          id: string;
          isScheduled?: boolean;
          notes?: string | null;
          startTime: string;
          type: Database['public']['Enums']['activityType'];
          updatedAt?: string;
          userId?: string;
        };
        Update: {
          amount?: number | null;
          babyId?: string;
          createdAt?: string;
          details?: Json | null;
          duration?: number | null;
          endTime?: string | null;
          feedingSource?: Database['public']['Enums']['feedingSource'] | null;
          id?: string;
          isScheduled?: boolean;
          notes?: string | null;
          startTime?: string;
          type?: Database['public']['Enums']['activityType'];
          updatedAt?: string;
          userId?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'activities_babyId_babies_id_fk';
            columns: ['babyId'];
            isOneToOne: false;
            referencedRelation: 'babies';
            referencedColumns: ['id'];
          },
        ];
      };
      babies: {
        Row: {
          birthDate: string | null;
          birthWeightOz: number | null;
          createdAt: string;
          currentWeightOz: number | null;
          dueDate: string | null;
          familyId: string;
          feedIntervalHours: number | null;
          firstName: string;
          gender: string | null;
          id: string;
          journeyStage: Database['public']['Enums']['journeyStage'] | null;
          lastName: string | null;
          metadata: Json | null;
          middleName: string | null;
          mlPerPump: number | null;
          photoUrl: string | null;
          pumpsPerDay: number | null;
          ttcMethod: Database['public']['Enums']['ttcMethod'] | null;
          updatedAt: string;
          userId: string;
        };
        Insert: {
          birthDate?: string | null;
          birthWeightOz?: number | null;
          createdAt?: string;
          currentWeightOz?: number | null;
          dueDate?: string | null;
          familyId?: string;
          feedIntervalHours?: number | null;
          firstName: string;
          gender?: string | null;
          id: string;
          journeyStage?: Database['public']['Enums']['journeyStage'] | null;
          lastName?: string | null;
          metadata?: Json | null;
          middleName?: string | null;
          mlPerPump?: number | null;
          photoUrl?: string | null;
          pumpsPerDay?: number | null;
          ttcMethod?: Database['public']['Enums']['ttcMethod'] | null;
          updatedAt?: string;
          userId?: string;
        };
        Update: {
          birthDate?: string | null;
          birthWeightOz?: number | null;
          createdAt?: string;
          currentWeightOz?: number | null;
          dueDate?: string | null;
          familyId?: string;
          feedIntervalHours?: number | null;
          firstName?: string;
          gender?: string | null;
          id?: string;
          journeyStage?: Database['public']['Enums']['journeyStage'] | null;
          lastName?: string | null;
          metadata?: Json | null;
          middleName?: string | null;
          mlPerPump?: number | null;
          photoUrl?: string | null;
          pumpsPerDay?: number | null;
          ttcMethod?: Database['public']['Enums']['ttcMethod'] | null;
          updatedAt?: string;
          userId?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'babies_familyId_families_id_fk';
            columns: ['familyId'];
            isOneToOne: false;
            referencedRelation: 'families';
            referencedColumns: ['id'];
          },
        ];
      };
      families: {
        Row: {
          clerkOrgId: string;
          createdAt: string | null;
          createdByUserId: string;
          id: string;
          name: string;
          stripeCustomerId: string | null;
          stripeSubscriptionId: string | null;
          stripeSubscriptionStatus:
            | Database['public']['Enums']['stripeSubscriptionStatus']
            | null;
          updatedAt: string | null;
        };
        Insert: {
          clerkOrgId: string;
          createdAt?: string | null;
          createdByUserId: string;
          id: string;
          name: string;
          stripeCustomerId?: string | null;
          stripeSubscriptionId?: string | null;
          stripeSubscriptionStatus?:
            | Database['public']['Enums']['stripeSubscriptionStatus']
            | null;
          updatedAt?: string | null;
        };
        Update: {
          clerkOrgId?: string;
          createdAt?: string | null;
          createdByUserId?: string;
          id?: string;
          name?: string;
          stripeCustomerId?: string | null;
          stripeSubscriptionId?: string | null;
          stripeSubscriptionStatus?:
            | Database['public']['Enums']['stripeSubscriptionStatus']
            | null;
          updatedAt?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'families_createdByUserId_users_id_fk';
            columns: ['createdByUserId'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      familyMembers: {
        Row: {
          createdAt: string | null;
          familyId: string;
          id: string;
          onboardingCompletedAt: string | null;
          role: Database['public']['Enums']['userRole'];
          updatedAt: string | null;
          userId: string;
          userRole: Database['public']['Enums']['userRole'] | null;
        };
        Insert: {
          createdAt?: string | null;
          familyId?: string;
          id: string;
          onboardingCompletedAt?: string | null;
          role?: Database['public']['Enums']['userRole'];
          updatedAt?: string | null;
          userId?: string;
          userRole?: Database['public']['Enums']['userRole'] | null;
        };
        Update: {
          createdAt?: string | null;
          familyId?: string;
          id?: string;
          onboardingCompletedAt?: string | null;
          role?: Database['public']['Enums']['userRole'];
          updatedAt?: string | null;
          userId?: string;
          userRole?: Database['public']['Enums']['userRole'] | null;
        };
        Relationships: [
          {
            foreignKeyName: 'familyMembers_familyId_families_id_fk';
            columns: ['familyId'];
            isOneToOne: false;
            referencedRelation: 'families';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'familyMembers_userId_users_id_fk';
            columns: ['userId'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      growthRecords: {
        Row: {
          babyId: string;
          createdAt: string;
          date: string;
          headCircumference: number | null;
          height: number | null;
          id: string;
          metadata: Json | null;
          notes: string | null;
          updatedAt: string;
          userId: string;
          weight: number | null;
        };
        Insert: {
          babyId: string;
          createdAt?: string;
          date: string;
          headCircumference?: number | null;
          height?: number | null;
          id: string;
          metadata?: Json | null;
          notes?: string | null;
          updatedAt?: string;
          userId?: string;
          weight?: number | null;
        };
        Update: {
          babyId?: string;
          createdAt?: string;
          date?: string;
          headCircumference?: number | null;
          height?: number | null;
          id?: string;
          metadata?: Json | null;
          notes?: string | null;
          updatedAt?: string;
          userId?: string;
          weight?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: 'growthRecords_babyId_babies_id_fk';
            columns: ['babyId'];
            isOneToOne: false;
            referencedRelation: 'babies';
            referencedColumns: ['id'];
          },
        ];
      };
      invitations: {
        Row: {
          code: string;
          createdAt: string | null;
          expiresAt: string;
          familyId: string;
          id: string;
          invitedByUserId: string;
          isActive: boolean;
          role: Database['public']['Enums']['userRole'];
          updatedAt: string | null;
          usedAt: string | null;
          usedByUserId: string | null;
        };
        Insert: {
          code: string;
          createdAt?: string | null;
          expiresAt: string;
          familyId?: string;
          id: string;
          invitedByUserId?: string;
          isActive?: boolean;
          role?: Database['public']['Enums']['userRole'];
          updatedAt?: string | null;
          usedAt?: string | null;
          usedByUserId?: string | null;
        };
        Update: {
          code?: string;
          createdAt?: string | null;
          expiresAt?: string;
          familyId?: string;
          id?: string;
          invitedByUserId?: string;
          isActive?: boolean;
          role?: Database['public']['Enums']['userRole'];
          updatedAt?: string | null;
          usedAt?: string | null;
          usedByUserId?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'invitations_familyId_families_id_fk';
            columns: ['familyId'];
            isOneToOne: false;
            referencedRelation: 'families';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'invitations_invitedByUserId_users_id_fk';
            columns: ['invitedByUserId'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'invitations_usedByUserId_users_id_fk';
            columns: ['usedByUserId'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      medicalRecords: {
        Row: {
          babyId: string;
          createdAt: string;
          date: string;
          description: string | null;
          id: string;
          location: string | null;
          metadata: Json | null;
          provider: string | null;
          title: string;
          type: string;
          updatedAt: string;
          userId: string;
        };
        Insert: {
          babyId: string;
          createdAt?: string;
          date: string;
          description?: string | null;
          id: string;
          location?: string | null;
          metadata?: Json | null;
          provider?: string | null;
          title: string;
          type: string;
          updatedAt?: string;
          userId?: string;
        };
        Update: {
          babyId?: string;
          createdAt?: string;
          date?: string;
          description?: string | null;
          id?: string;
          location?: string | null;
          metadata?: Json | null;
          provider?: string | null;
          title?: string;
          type?: string;
          updatedAt?: string;
          userId?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'medicalRecords_babyId_babies_id_fk';
            columns: ['babyId'];
            isOneToOne: false;
            referencedRelation: 'babies';
            referencedColumns: ['id'];
          },
        ];
      };
      milestones: {
        Row: {
          achievedDate: string;
          babyId: string;
          createdAt: string;
          description: string | null;
          id: string;
          metadata: Json | null;
          photoUrl: string | null;
          title: string;
          type: Database['public']['Enums']['milestoneType'];
          updatedAt: string;
          userId: string;
        };
        Insert: {
          achievedDate: string;
          babyId: string;
          createdAt?: string;
          description?: string | null;
          id: string;
          metadata?: Json | null;
          photoUrl?: string | null;
          title: string;
          type: Database['public']['Enums']['milestoneType'];
          updatedAt?: string;
          userId?: string;
        };
        Update: {
          achievedDate?: string;
          babyId?: string;
          createdAt?: string;
          description?: string | null;
          id?: string;
          metadata?: Json | null;
          photoUrl?: string | null;
          title?: string;
          type?: Database['public']['Enums']['milestoneType'];
          updatedAt?: string;
          userId?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'milestones_babyId_babies_id_fk';
            columns: ['babyId'];
            isOneToOne: false;
            referencedRelation: 'babies';
            referencedColumns: ['id'];
          },
        ];
      };
      pushSubscriptions: {
        Row: {
          auth: string;
          createdAt: string | null;
          endpoint: string;
          id: string;
          p256dh: string;
          updatedAt: string | null;
          userId: string;
        };
        Insert: {
          auth: string;
          createdAt?: string | null;
          endpoint: string;
          id: string;
          p256dh: string;
          updatedAt?: string | null;
          userId?: string;
        };
        Update: {
          auth?: string;
          createdAt?: string | null;
          endpoint?: string;
          id?: string;
          p256dh?: string;
          updatedAt?: string | null;
          userId?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'pushSubscriptions_userId_users_id_fk';
            columns: ['userId'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      shortUrls: {
        Row: {
          code: string;
          createdAt: string | null;
          expiresAt: string | null;
          familyId: string;
          id: string;
          isActive: boolean;
          redirectUrl: string;
          updatedAt: string | null;
          userId: string;
        };
        Insert: {
          code: string;
          createdAt?: string | null;
          expiresAt?: string | null;
          familyId?: string;
          id: string;
          isActive?: boolean;
          redirectUrl: string;
          updatedAt?: string | null;
          userId?: string;
        };
        Update: {
          code?: string;
          createdAt?: string | null;
          expiresAt?: string | null;
          familyId?: string;
          id?: string;
          isActive?: boolean;
          redirectUrl?: string;
          updatedAt?: string | null;
          userId?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'shortUrls_familyId_families_id_fk';
            columns: ['familyId'];
            isOneToOne: false;
            referencedRelation: 'families';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'shortUrls_userId_users_id_fk';
            columns: ['userId'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      supplyInventory: {
        Row: {
          babyId: string;
          createdAt: string;
          donorMl: number;
          formulaMl: number;
          id: string;
          pumpedMl: number;
          updatedAt: string;
          userId: string;
        };
        Insert: {
          babyId: string;
          createdAt?: string;
          donorMl?: number;
          formulaMl?: number;
          id: string;
          pumpedMl?: number;
          updatedAt?: string;
          userId?: string;
        };
        Update: {
          babyId?: string;
          createdAt?: string;
          donorMl?: number;
          formulaMl?: number;
          id?: string;
          pumpedMl?: number;
          updatedAt?: string;
          userId?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'supplyInventory_babyId_babies_id_fk';
            columns: ['babyId'];
            isOneToOne: false;
            referencedRelation: 'babies';
            referencedColumns: ['id'];
          },
        ];
      };
      supplyTransactions: {
        Row: {
          amountMl: number;
          babyId: string;
          createdAt: string;
          id: string;
          notes: string | null;
          source: Database['public']['Enums']['feedingSource'];
          timestamp: string;
          type: Database['public']['Enums']['supplyTransactionType'];
          updatedAt: string;
          userId: string;
        };
        Insert: {
          amountMl: number;
          babyId: string;
          createdAt?: string;
          id: string;
          notes?: string | null;
          source: Database['public']['Enums']['feedingSource'];
          timestamp?: string;
          type: Database['public']['Enums']['supplyTransactionType'];
          updatedAt?: string;
          userId?: string;
        };
        Update: {
          amountMl?: number;
          babyId?: string;
          createdAt?: string;
          id?: string;
          notes?: string | null;
          source?: Database['public']['Enums']['feedingSource'];
          timestamp?: string;
          type?: Database['public']['Enums']['supplyTransactionType'];
          updatedAt?: string;
          userId?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'supplyTransactions_babyId_babies_id_fk';
            columns: ['babyId'];
            isOneToOne: false;
            referencedRelation: 'babies';
            referencedColumns: ['id'];
          },
        ];
      };
      users: {
        Row: {
          avatarUrl: string | null;
          clerkId: string;
          createdAt: string;
          email: string;
          firstName: string | null;
          id: string;
          lastLoggedInAt: string | null;
          lastName: string | null;
          measurementUnit: Database['public']['Enums']['measurementUnit'];
          online: boolean;
          temperatureUnit: Database['public']['Enums']['temperatureUnit'];
          theme: Database['public']['Enums']['theme'];
          timeFormat: Database['public']['Enums']['timeFormat'];
          unitPref: Database['public']['Enums']['unitPref'];
          updatedAt: string | null;
        };
        Insert: {
          avatarUrl?: string | null;
          clerkId: string;
          createdAt?: string;
          email: string;
          firstName?: string | null;
          id: string;
          lastLoggedInAt?: string | null;
          lastName?: string | null;
          measurementUnit?: Database['public']['Enums']['measurementUnit'];
          online?: boolean;
          temperatureUnit?: Database['public']['Enums']['temperatureUnit'];
          theme?: Database['public']['Enums']['theme'];
          timeFormat?: Database['public']['Enums']['timeFormat'];
          unitPref?: Database['public']['Enums']['unitPref'];
          updatedAt?: string | null;
        };
        Update: {
          avatarUrl?: string | null;
          clerkId?: string;
          createdAt?: string;
          email?: string;
          firstName?: string | null;
          id?: string;
          lastLoggedInAt?: string | null;
          lastName?: string | null;
          measurementUnit?: Database['public']['Enums']['measurementUnit'];
          online?: boolean;
          temperatureUnit?: Database['public']['Enums']['temperatureUnit'];
          theme?: Database['public']['Enums']['theme'];
          timeFormat?: Database['public']['Enums']['timeFormat'];
          unitPref?: Database['public']['Enums']['unitPref'];
          updatedAt?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      requesting_family_id: { Args: never; Returns: string };
      requesting_user_id: { Args: never; Returns: string };
    };
    Enums: {
      activityType:
        | 'sleep'
        | 'feeding'
        | 'bottle'
        | 'nursing'
        | 'pumping'
        | 'diaper'
        | 'wet'
        | 'dirty'
        | 'both'
        | 'solids'
        | 'bath'
        | 'medicine'
        | 'temperature'
        | 'tummy_time'
        | 'growth'
        | 'potty';
      feedingSource: 'pumped' | 'donor' | 'direct' | 'formula';
      journeyStage: 'ttc' | 'pregnant' | 'born';
      localConnectionStatus: 'connected' | 'disconnected';
      measurementUnit: 'imperial' | 'metric';
      milestoneType:
        | 'physical'
        | 'cognitive'
        | 'social'
        | 'language'
        | 'self_care';
      stripeSubscriptionStatus:
        | 'active'
        | 'canceled'
        | 'incomplete'
        | 'incomplete_expired'
        | 'past_due'
        | 'paused'
        | 'trialing'
        | 'unpaid';
      supplyTransactionType: 'add' | 'deduct';
      temperatureUnit: 'fahrenheit' | 'celsius';
      theme: 'light' | 'dark' | 'system';
      timeFormat: '12h' | '24h';
      ttcMethod: 'natural' | 'ivf' | 'other';
      unitPref: 'ML' | 'OZ';
      userRole: 'primary' | 'partner' | 'caregiver';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  'public'
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      activityType: [
        'sleep',
        'feeding',
        'bottle',
        'nursing',
        'pumping',
        'diaper',
        'wet',
        'dirty',
        'both',
        'solids',
        'bath',
        'medicine',
        'temperature',
        'tummy_time',
        'growth',
        'potty',
      ],
      feedingSource: ['pumped', 'donor', 'direct', 'formula'],
      journeyStage: ['ttc', 'pregnant', 'born'],
      localConnectionStatus: ['connected', 'disconnected'],
      measurementUnit: ['imperial', 'metric'],
      milestoneType: [
        'physical',
        'cognitive',
        'social',
        'language',
        'self_care',
      ],
      stripeSubscriptionStatus: [
        'active',
        'canceled',
        'incomplete',
        'incomplete_expired',
        'past_due',
        'paused',
        'trialing',
        'unpaid',
      ],
      supplyTransactionType: ['add', 'deduct'],
      temperatureUnit: ['fahrenheit', 'celsius'],
      theme: ['light', 'dark', 'system'],
      timeFormat: ['12h', '24h'],
      ttcMethod: ['natural', 'ivf', 'other'],
      unitPref: ['ML', 'OZ'],
      userRole: ['primary', 'partner', 'caregiver'],
    },
  },
} as const;
