/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AppointmentNudgeOutput,  BabyAssistantChatOutput,  BabyContext,  BabyVisitExplainerOutput,  BirthPlanHeadlineOutput,  CelebrationQuestion,  CelebrationQuestionsOutput,  CelebrationStatistics,  CelebrationSummaryOutput,  ChatMessage,  ChatTitleOutput,  CheckInQuestion,  ContextualMilestonesOutput,  DailyCheckInQuestionsOutput,  DailyLearningPlan,  DoctorQuestionsOutput,  HospitalPackAdviceOutput,  ImprovementSuggestions,  LearningPlanItem,  LearningTip,  MilestoneEnhancementOutput,  MilestoneExplanationOutput,  MilestoneInput,  MilestonePlan,  MilestonePlanItem,  MilestoneSuggestion,  NewbornMilestoneOutput,  ParentTask,  ParentTip,  PersonalizedTasksOutput,  PostpartumTipsInput,  PostpartumTipsOutput,  PregnancyWeekSummaryOutput,  ResponseType,  RoleSpecificTipsOutput,  SleepRegressionTipsOutput,  StalePromptsOutput,  WellnessQuestion,  WellnessScreeningOutput } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AppointmentNudgeOutput {
      text?: string | null
    }
    export interface BabyAssistantChatOutput {
      response?: string | null
    }
    export interface BabyContext {
      babyName?: string | null
      ageInDays?: number | null
      ageInWeeks?: number | null
      currentWeightOz?: number | null
      birthWeightOz?: number | null
      feedingCount24h?: number | null
      avgFeedingInterval?: number | null
      sleepCount24h?: number | null
      totalSleepHours24h?: number | null
      diaperCount24h?: number | null
    }
    export interface BabyVisitExplainerOutput {
      text?: string | null
    }
    export interface BirthPlanHeadlineOutput {
      text?: string | null
    }
    export interface CelebrationQuestion {
      question?: string | null
      systemPrompt?: string | null
      buttonLabel?: string | null
      icon?: string | null
    }
    export interface CelebrationQuestionsOutput {
      milestone?: CelebrationQuestion | null
      memory?: CelebrationQuestion | null
      guidance?: CelebrationQuestion | null
    }
    export interface CelebrationStatistics {
      ageInDays?: number | null
      ageLabel?: string | null
      feedingCount?: number | null
      sleepHours?: number | null
      diaperCount?: number | null
      weightGain?: string | null
    }
    export interface CelebrationSummaryOutput {
      summary?: string | null
    }
    export interface ChatMessage {
      role?: string | null
      content?: string | null
    }
    export interface ChatTitleOutput {
      title?: string | null
    }
    export interface CheckInQuestion {
      question?: string | null
      responseType?: types.ResponseType | null
      category?: string | null
      priority?: string | null
      followUpPrompt?: string | null
    }
    export interface ContextualMilestonesOutput {
      milestones: MilestoneSuggestion[]
    }
    export interface DailyCheckInQuestionsOutput {
      questions: CheckInQuestion[]
    }
    export interface DailyLearningPlan {
      items: LearningPlanItem[]
      reasoning?: string | null
      coveredCategories: string[]
      urgentHealthChecks?: boolean | null
    }
    export interface DoctorQuestionsOutput {
      summary?: string | null
      questions: string[]
      concerns: string[]
    }
    export interface HospitalPackAdviceOutput {
      headline?: string | null
      subtext?: string | null
    }
    export interface ImprovementSuggestions {
      seo: string[]
      accessibility: string[]
      performance: string[]
      overall_priority: string[]
    }
    export interface LearningPlanItem {
      category?: string | null
      title?: string | null
      subtitle?: string | null
      relevance?: string | null
      priority?: number | null
      avoidDuplicateOf: string[]
      recommendYesNo?: boolean | null
    }
    export interface LearningTip {
      category?: string | null
      subtitle?: string | null
      summary?: string | null
      bulletPoints: string[]
      followUpQuestion?: string | null
      isYesNoQuestion?: boolean | null
      openChatOnYes?: boolean | null
      openChatOnNo?: boolean | null
    }
    export interface MilestoneEnhancementOutput {
      subtitle?: string | null
      summary?: string | null
      bulletPoints: string[]
      followUpQuestion?: string | null
      isYesNoQuestion?: boolean | null
      openChatOnYes?: boolean | null
      openChatOnNo?: boolean | null
    }
    export interface MilestoneExplanationOutput {
      explanation?: string | null
      whyItMatters?: string | null
      whatToExpect?: string | null
      tips: string[]
      reassurance?: string | null
    }
    export interface MilestoneInput {
      babyName?: string | null
      babySex?: string | null
      ageInDays?: number | null
      ageInWeeks?: number | null
      currentWeightOz?: number | null
      birthWeightOz?: number | null
      height?: number | null
      feedingCount24h?: number | null
      avgFeedingInterval?: number | null
      sleepCount24h?: number | null
      totalSleepHours24h?: number | null
      diaperCount24h?: number | null
      avgFeedingsPerDay?: number | null
      avgSleepHoursPerDay?: number | null
      avgDiaperChangesPerDay?: number | null
      recentChatTopics?: string | null
      achievedMilestones?: string | null
      activitySummary?: string | null
      hasTummyTimeActivity?: boolean | null
      medicalContext?: string | null
      plannedItem?: MilestonePlanItem | null
    }
    export interface MilestonePlan {
      items: MilestonePlanItem[]
      reasoning?: string | null
      coveredTypes: string[]
      developmentalFocus?: string | null
    }
    export interface MilestonePlanItem {
      title?: string | null
      type?: string | null
      ageLabel?: string | null
      relevance?: string | null
      priority?: number | null
      expectedInStage?: boolean | null
      avoidDuplicateOf: string[]
      recommendYesNo?: boolean | null
    }
    export interface MilestoneSuggestion {
      title?: string | null
      type?: string | null
      description?: string | null
      ageLabel?: string | null
      relevance?: string | null
    }
    export interface NewbornMilestoneOutput {
      tips: LearningTip[]
    }
    export interface ParentTask {
      taskText?: string | null
      category?: string | null
      priority?: string | null
      suggestedTime?: string | null
      estimatedMinutes?: number | null
      whyItMatters?: string | null
    }
    export interface ParentTip {
      title?: string | null
      content?: string | null
      actionItems: string[]
      relevantToRole?: string | null
    }
    export interface PersonalizedTasksOutput {
      tasks: ParentTask[]
      motivationalMessage?: string | null
    }
    export interface PostpartumTipsInput {
      babyName?: string | null
      babySex?: string | null
      day?: number | null
      firstPregnancy?: boolean | null
      ageInDays?: number | null
      ageInWeeks?: number | null
      currentWeightOz?: number | null
      birthWeightOz?: number | null
      height?: number | null
      headCircumference?: number | null
      feedingCount24h?: number | null
      avgFeedingInterval?: number | null
      sleepCount24h?: number | null
      totalSleepHours24h?: number | null
      diaperCount24h?: number | null
      avgFeedingsPerDay?: number | null
      avgSleepHoursPerDay?: number | null
      avgDiaperChangesPerDay?: number | null
      recentChatTopics?: string | null
      achievedMilestones?: string | null
      activitySummary?: string | null
      parentWellness?: string | null
      medicalContext?: string | null
    }
    export interface PostpartumTipsOutput {
      tips: LearningTip[]
    }
    export interface PregnancyWeekSummaryOutput {
      text?: string | null
    }
    export interface RoleSpecificTipsOutput {
      tips: ParentTip[]
    }
    export interface SleepRegressionTipsOutput {
      tips: LearningTip[]
    }
    export interface StalePromptsOutput {
      list: string[]
    }
    export interface WellnessQuestion {
      question?: string | null
      responseType?: string | null
      category?: string | null
      weight?: number | null
      reverseScore?: boolean | null
    }
    export interface WellnessScreeningOutput {
      questions: WellnessQuestion[]
      scoringGuidance?: string | null
      supportResources: string[]
    }
}