/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AppointmentNudgeOutput: ClassViewer<'AppointmentNudgeOutput', "text">;
    
    BabyVisitExplainerOutput: ClassViewer<'BabyVisitExplainerOutput', "text">;
    
    BirthPlanHeadlineOutput: ClassViewer<'BirthPlanHeadlineOutput', "text">;
    
    HospitalPackAdviceOutput: ClassViewer<'HospitalPackAdviceOutput', "headline" | "subtext">;
    
    ImprovementSuggestions: ClassViewer<'ImprovementSuggestions', "seo" | "accessibility" | "performance" | "overall_priority">;
    
    NewbornMilestoneOutput: ClassViewer<'NewbornMilestoneOutput', "text">;
    
    PostpartumTipsOutput: ClassViewer<'PostpartumTipsOutput', "text">;
    
    PregnancyWeekSummaryOutput: ClassViewer<'PregnancyWeekSummaryOutput', "text">;
    
    SleepRegressionTipsOutput: ClassViewer<'SleepRegressionTipsOutput', "snippet">;
    
    StalePromptsOutput: ClassViewer<'StalePromptsOutput', "list">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AppointmentNudgeOutput","BabyVisitExplainerOutput","BirthPlanHeadlineOutput","HospitalPackAdviceOutput","ImprovementSuggestions","NewbornMilestoneOutput","PostpartumTipsOutput","PregnancyWeekSummaryOutput","SleepRegressionTipsOutput","StalePromptsOutput",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AppointmentNudgeOutput = this.tb.classViewer("AppointmentNudgeOutput", [
          "text",
        ]);
        
        this.BabyVisitExplainerOutput = this.tb.classViewer("BabyVisitExplainerOutput", [
          "text",
        ]);
        
        this.BirthPlanHeadlineOutput = this.tb.classViewer("BirthPlanHeadlineOutput", [
          "text",
        ]);
        
        this.HospitalPackAdviceOutput = this.tb.classViewer("HospitalPackAdviceOutput", [
          "headline","subtext",
        ]);
        
        this.ImprovementSuggestions = this.tb.classViewer("ImprovementSuggestions", [
          "seo","accessibility","performance","overall_priority",
        ]);
        
        this.NewbornMilestoneOutput = this.tb.classViewer("NewbornMilestoneOutput", [
          "text",
        ]);
        
        this.PostpartumTipsOutput = this.tb.classViewer("PostpartumTipsOutput", [
          "text",
        ]);
        
        this.PregnancyWeekSummaryOutput = this.tb.classViewer("PregnancyWeekSummaryOutput", [
          "text",
        ]);
        
        this.SleepRegressionTipsOutput = this.tb.classViewer("SleepRegressionTipsOutput", [
          "snippet",
        ]);
        
        this.StalePromptsOutput = this.tb.classViewer("StalePromptsOutput", [
          "list",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}