/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AppointmentNudgeOutput: ClassViewer<'AppointmentNudgeOutput', "text">;
    
    BabyAssistantChatOutput: ClassViewer<'BabyAssistantChatOutput', "response">;
    
    BabyContext: ClassViewer<'BabyContext', "babyName" | "ageInDays" | "ageInWeeks" | "currentWeightOz" | "birthWeightOz" | "feedingCount24h" | "avgFeedingInterval" | "sleepCount24h" | "totalSleepHours24h" | "diaperCount24h">;
    
    BabyVisitExplainerOutput: ClassViewer<'BabyVisitExplainerOutput', "text">;
    
    BirthPlanHeadlineOutput: ClassViewer<'BirthPlanHeadlineOutput', "text">;
    
    ChatMessage: ClassViewer<'ChatMessage', "role" | "content">;
    
    ChatTitleOutput: ClassViewer<'ChatTitleOutput', "title">;
    
    CheckInQuestion: ClassViewer<'CheckInQuestion', "question" | "responseType" | "category" | "priority" | "followUpPrompt">;
    
    ContextualMilestonesOutput: ClassViewer<'ContextualMilestonesOutput', "milestones">;
    
    DailyCheckInQuestionsOutput: ClassViewer<'DailyCheckInQuestionsOutput', "questions">;
    
    DailyLearningPlan: ClassViewer<'DailyLearningPlan', "items" | "reasoning" | "coveredCategories" | "urgentHealthChecks">;
    
    HospitalPackAdviceOutput: ClassViewer<'HospitalPackAdviceOutput', "headline" | "subtext">;
    
    ImprovementSuggestions: ClassViewer<'ImprovementSuggestions', "seo" | "accessibility" | "performance" | "overall_priority">;
    
    LearningPlanItem: ClassViewer<'LearningPlanItem', "category" | "title" | "subtitle" | "relevance" | "priority" | "avoidDuplicateOf" | "recommendYesNo">;
    
    LearningTip: ClassViewer<'LearningTip', "category" | "subtitle" | "summary" | "bulletPoints" | "followUpQuestion" | "isYesNoQuestion" | "openChatOnYes" | "openChatOnNo">;
    
    MilestoneEnhancementOutput: ClassViewer<'MilestoneEnhancementOutput', "subtitle" | "summary" | "bulletPoints" | "followUpQuestion" | "isYesNoQuestion" | "openChatOnYes" | "openChatOnNo">;
    
    MilestoneExplanationOutput: ClassViewer<'MilestoneExplanationOutput', "explanation" | "whyItMatters" | "whatToExpect" | "tips" | "reassurance">;
    
    MilestoneInput: ClassViewer<'MilestoneInput', "babyName" | "babySex" | "ageInDays" | "ageInWeeks" | "currentWeightOz" | "birthWeightOz" | "height" | "feedingCount24h" | "avgFeedingInterval" | "sleepCount24h" | "totalSleepHours24h" | "diaperCount24h" | "avgFeedingsPerDay" | "avgSleepHoursPerDay" | "avgDiaperChangesPerDay" | "recentChatTopics" | "achievedMilestones" | "activitySummary" | "hasTummyTimeActivity" | "medicalContext" | "plannedItem">;
    
    MilestonePlan: ClassViewer<'MilestonePlan', "items" | "reasoning" | "coveredTypes" | "developmentalFocus">;
    
    MilestonePlanItem: ClassViewer<'MilestonePlanItem', "title" | "type" | "ageLabel" | "relevance" | "priority" | "expectedInStage" | "avoidDuplicateOf" | "recommendYesNo">;
    
    MilestoneSuggestion: ClassViewer<'MilestoneSuggestion', "title" | "type" | "description" | "ageLabel" | "relevance">;
    
    NewbornMilestoneOutput: ClassViewer<'NewbornMilestoneOutput', "tips">;
    
    ParentTask: ClassViewer<'ParentTask', "taskText" | "category" | "priority" | "suggestedTime" | "estimatedMinutes" | "whyItMatters">;
    
    ParentTip: ClassViewer<'ParentTip', "title" | "content" | "actionItems" | "relevantToRole">;
    
    PersonalizedTasksOutput: ClassViewer<'PersonalizedTasksOutput', "tasks" | "motivationalMessage">;
    
    PostpartumTipsInput: ClassViewer<'PostpartumTipsInput', "babyName" | "babySex" | "day" | "firstPregnancy" | "ageInDays" | "ageInWeeks" | "currentWeightOz" | "birthWeightOz" | "height" | "headCircumference" | "feedingCount24h" | "avgFeedingInterval" | "sleepCount24h" | "totalSleepHours24h" | "diaperCount24h" | "avgFeedingsPerDay" | "avgSleepHoursPerDay" | "avgDiaperChangesPerDay" | "recentChatTopics" | "achievedMilestones" | "activitySummary" | "parentWellness" | "medicalContext">;
    
    PostpartumTipsOutput: ClassViewer<'PostpartumTipsOutput', "tips">;
    
    PregnancyWeekSummaryOutput: ClassViewer<'PregnancyWeekSummaryOutput', "text">;
    
    RoleSpecificTipsOutput: ClassViewer<'RoleSpecificTipsOutput', "tips">;
    
    SleepRegressionTipsOutput: ClassViewer<'SleepRegressionTipsOutput', "tips">;
    
    StalePromptsOutput: ClassViewer<'StalePromptsOutput', "list">;
    
    WellnessQuestion: ClassViewer<'WellnessQuestion', "question" | "responseType" | "category" | "weight" | "reverseScore">;
    
    WellnessScreeningOutput: ClassViewer<'WellnessScreeningOutput', "questions" | "scoringGuidance" | "supportResources">;
    
    
    ResponseType: EnumViewer<'ResponseType', "EMOJI_SCALE" | "YES_NO" | "RATING_1_5" | "TEXT_SHORT">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AppointmentNudgeOutput","BabyAssistantChatOutput","BabyContext","BabyVisitExplainerOutput","BirthPlanHeadlineOutput","ChatMessage","ChatTitleOutput","CheckInQuestion","ContextualMilestonesOutput","DailyCheckInQuestionsOutput","DailyLearningPlan","HospitalPackAdviceOutput","ImprovementSuggestions","LearningPlanItem","LearningTip","MilestoneEnhancementOutput","MilestoneExplanationOutput","MilestoneInput","MilestonePlan","MilestonePlanItem","MilestoneSuggestion","NewbornMilestoneOutput","ParentTask","ParentTip","PersonalizedTasksOutput","PostpartumTipsInput","PostpartumTipsOutput","PregnancyWeekSummaryOutput","RoleSpecificTipsOutput","SleepRegressionTipsOutput","StalePromptsOutput","WellnessQuestion","WellnessScreeningOutput",
          ]),
          enums: new Set([
            "ResponseType",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AppointmentNudgeOutput = this.tb.classViewer("AppointmentNudgeOutput", [
          "text",
        ]);
        
        this.BabyAssistantChatOutput = this.tb.classViewer("BabyAssistantChatOutput", [
          "response",
        ]);
        
        this.BabyContext = this.tb.classViewer("BabyContext", [
          "babyName","ageInDays","ageInWeeks","currentWeightOz","birthWeightOz","feedingCount24h","avgFeedingInterval","sleepCount24h","totalSleepHours24h","diaperCount24h",
        ]);
        
        this.BabyVisitExplainerOutput = this.tb.classViewer("BabyVisitExplainerOutput", [
          "text",
        ]);
        
        this.BirthPlanHeadlineOutput = this.tb.classViewer("BirthPlanHeadlineOutput", [
          "text",
        ]);
        
        this.ChatMessage = this.tb.classViewer("ChatMessage", [
          "role","content",
        ]);
        
        this.ChatTitleOutput = this.tb.classViewer("ChatTitleOutput", [
          "title",
        ]);
        
        this.CheckInQuestion = this.tb.classViewer("CheckInQuestion", [
          "question","responseType","category","priority","followUpPrompt",
        ]);
        
        this.ContextualMilestonesOutput = this.tb.classViewer("ContextualMilestonesOutput", [
          "milestones",
        ]);
        
        this.DailyCheckInQuestionsOutput = this.tb.classViewer("DailyCheckInQuestionsOutput", [
          "questions",
        ]);
        
        this.DailyLearningPlan = this.tb.classViewer("DailyLearningPlan", [
          "items","reasoning","coveredCategories","urgentHealthChecks",
        ]);
        
        this.HospitalPackAdviceOutput = this.tb.classViewer("HospitalPackAdviceOutput", [
          "headline","subtext",
        ]);
        
        this.ImprovementSuggestions = this.tb.classViewer("ImprovementSuggestions", [
          "seo","accessibility","performance","overall_priority",
        ]);
        
        this.LearningPlanItem = this.tb.classViewer("LearningPlanItem", [
          "category","title","subtitle","relevance","priority","avoidDuplicateOf","recommendYesNo",
        ]);
        
        this.LearningTip = this.tb.classViewer("LearningTip", [
          "category","subtitle","summary","bulletPoints","followUpQuestion","isYesNoQuestion","openChatOnYes","openChatOnNo",
        ]);
        
        this.MilestoneEnhancementOutput = this.tb.classViewer("MilestoneEnhancementOutput", [
          "subtitle","summary","bulletPoints","followUpQuestion","isYesNoQuestion","openChatOnYes","openChatOnNo",
        ]);
        
        this.MilestoneExplanationOutput = this.tb.classViewer("MilestoneExplanationOutput", [
          "explanation","whyItMatters","whatToExpect","tips","reassurance",
        ]);
        
        this.MilestoneInput = this.tb.classViewer("MilestoneInput", [
          "babyName","babySex","ageInDays","ageInWeeks","currentWeightOz","birthWeightOz","height","feedingCount24h","avgFeedingInterval","sleepCount24h","totalSleepHours24h","diaperCount24h","avgFeedingsPerDay","avgSleepHoursPerDay","avgDiaperChangesPerDay","recentChatTopics","achievedMilestones","activitySummary","hasTummyTimeActivity","medicalContext","plannedItem",
        ]);
        
        this.MilestonePlan = this.tb.classViewer("MilestonePlan", [
          "items","reasoning","coveredTypes","developmentalFocus",
        ]);
        
        this.MilestonePlanItem = this.tb.classViewer("MilestonePlanItem", [
          "title","type","ageLabel","relevance","priority","expectedInStage","avoidDuplicateOf","recommendYesNo",
        ]);
        
        this.MilestoneSuggestion = this.tb.classViewer("MilestoneSuggestion", [
          "title","type","description","ageLabel","relevance",
        ]);
        
        this.NewbornMilestoneOutput = this.tb.classViewer("NewbornMilestoneOutput", [
          "tips",
        ]);
        
        this.ParentTask = this.tb.classViewer("ParentTask", [
          "taskText","category","priority","suggestedTime","estimatedMinutes","whyItMatters",
        ]);
        
        this.ParentTip = this.tb.classViewer("ParentTip", [
          "title","content","actionItems","relevantToRole",
        ]);
        
        this.PersonalizedTasksOutput = this.tb.classViewer("PersonalizedTasksOutput", [
          "tasks","motivationalMessage",
        ]);
        
        this.PostpartumTipsInput = this.tb.classViewer("PostpartumTipsInput", [
          "babyName","babySex","day","firstPregnancy","ageInDays","ageInWeeks","currentWeightOz","birthWeightOz","height","headCircumference","feedingCount24h","avgFeedingInterval","sleepCount24h","totalSleepHours24h","diaperCount24h","avgFeedingsPerDay","avgSleepHoursPerDay","avgDiaperChangesPerDay","recentChatTopics","achievedMilestones","activitySummary","parentWellness","medicalContext",
        ]);
        
        this.PostpartumTipsOutput = this.tb.classViewer("PostpartumTipsOutput", [
          "tips",
        ]);
        
        this.PregnancyWeekSummaryOutput = this.tb.classViewer("PregnancyWeekSummaryOutput", [
          "text",
        ]);
        
        this.RoleSpecificTipsOutput = this.tb.classViewer("RoleSpecificTipsOutput", [
          "tips",
        ]);
        
        this.SleepRegressionTipsOutput = this.tb.classViewer("SleepRegressionTipsOutput", [
          "tips",
        ]);
        
        this.StalePromptsOutput = this.tb.classViewer("StalePromptsOutput", [
          "list",
        ]);
        
        this.WellnessQuestion = this.tb.classViewer("WellnessQuestion", [
          "question","responseType","category","weight","reverseScore",
        ]);
        
        this.WellnessScreeningOutput = this.tb.classViewer("WellnessScreeningOutput", [
          "questions","scoringGuidance","supportResources",
        ]);
        
        
        this.ResponseType = this.tb.enumViewer("ResponseType", [
          "EMOJI_SCALE","YES_NO","RATING_1_5","TEXT_SHORT",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}