/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use client'

import type { BamlErrors } from '@boundaryml/baml/errors'
import { toBamlError } from '@boundaryml/baml/errors'
import { useCallback, useMemo, useReducer, useTransition } from 'react'
import * as Actions from './server'
import * as StreamingActions from './server_streaming'
import type { StreamingServerTypes } from './server_streaming_types'

/**
 * Type representing a BAML stream response.
 *
 * @template PartialType The type of the partial response.
 * @template FinalType The type of the final response.
 */
type BamlStreamResponse<PartialType, FinalType> = {
  partial?: PartialType
  final?: FinalType
  error?: BamlErrors
}

/**
 * A server action that returns either a ReadableStream of Uint8Array or a final output.
 */
export type ServerAction<Input = any, Output = any> = (
  ...args: Input extends any[] ? Input : [Input]
) => Promise<Output> | ReadableStream<Uint8Array>

/**
 * Type representing all function names except 'stream' and 'stream_types'
 */
export type FunctionNames = keyof typeof Actions

/**
 * Helper type to derive the partial return type for an action.
 */
type StreamDataType<FunctionName extends FunctionNames> = StreamingServerTypes[FunctionName]

/**
 * Helper type to derive the final return type for an action.
 */
type FinalDataType<FunctionName extends FunctionNames> = (typeof Actions)[FunctionName] extends (...args: any) => any
  ? Awaited<ReturnType<(typeof Actions)[FunctionName]>>
  : never

/**
 * Configuration options for BAML React hooks.
 */
export type HookInput<FunctionName extends FunctionNames = FunctionNames, Options extends { stream?: boolean } = { stream?: true }> = {
  stream?: Options['stream']
  onStreamData?: Options['stream'] extends false ? never : (response?: StreamDataType<FunctionName>) => void
  onFinalData?: (response?: FinalDataType<FunctionName>) => void
  onData?: (response?: Options['stream'] extends false ? FinalDataType<FunctionName> : FinalDataType<FunctionName> | StreamDataType<FunctionName>) => void
  onError?: (error: BamlErrors) => void
}

export type NonStreamingHookStatus = 'idle' | 'pending' | 'success' | 'error'
export type StreamingHookStatus = NonStreamingHookStatus | 'streaming'

export type HookStatus<Options extends { stream?: boolean } = { stream?: true }> = Options['stream'] extends false
  ? NonStreamingHookStatus
  : StreamingHookStatus

/**
 * Return type for BAML React hooks.
 */
export type HookOutput<FunctionName extends FunctionNames = FunctionNames, Options extends { stream?: boolean } = { stream?: true }> = {
  data?: Options['stream'] extends false ? FinalDataType<FunctionName> : FinalDataType<FunctionName> | StreamDataType<FunctionName>
  finalData?: FinalDataType<FunctionName>
  streamData?: Options['stream'] extends false ? never : StreamDataType<FunctionName>
  isLoading: boolean
  isPending: boolean
  isStreaming: Options['stream'] extends false ? never : boolean
  isSuccess: boolean
  isError: boolean
  error?: BamlErrors
  status: HookStatus<Options>
  mutate: (
    ...args: Parameters<(typeof Actions)[FunctionName]>
  ) => Options['stream'] extends false ? Promise<FinalDataType<FunctionName>> : Promise<ReadableStream<Uint8Array>>
  reset: () => void
}

export type HookData<FunctionName extends FunctionNames, Options extends { stream?: boolean } = { stream?: true }> = NonNullable<HookOutput<FunctionName, Options>['data']>;

/**
 * Type guard to check if the hook props are configured for streaming mode.
 *
 * @template FunctionName - The name of the BAML function.
 * @param props - The hook props.
 * @returns {boolean} True if the props indicate streaming mode.
 */
function isStreamingProps<FunctionName extends FunctionNames>(
  props: HookInput<FunctionName, { stream?: boolean }>,
): props is HookInput<FunctionName, { stream?: true }> {
  return props.stream !== false
}

interface HookState<TPartial, TFinal> {
  isSuccess: boolean
  isStreaming: boolean
  error?: BamlErrors
  finalData?: TFinal
  streamData?: TPartial
}

type HookStateAction<TPartial, TFinal> =
  | { type: 'START_REQUEST' }
  | { type: 'SET_ERROR'; payload: BamlErrors }
  | { type: 'SET_PARTIAL'; payload: TPartial }
  | { type: 'SET_FINAL'; payload: TFinal }
  | { type: 'RESET' }

/**
 * Reducer function to manage the hook state transitions.
 *
 * @template TPartial - The type of the partial (streaming) data.
 * @template TFinal - The type of the final (non‑streaming) data.
 * @param state - The current hook state.
 * @param action - The action to apply.
 * @returns The updated state.
 */
function hookReducer<TPartial, TFinal>(
  state: HookState<TPartial, TFinal>,
  action: HookStateAction<TPartial, TFinal>,
): HookState<TPartial, TFinal> {
  switch (action.type) {
    case 'START_REQUEST':
      return {
        ...state,
        isSuccess: false,
        error: undefined,
        isStreaming: false,
        finalData: undefined,
        streamData: undefined,
      }
    case 'SET_ERROR':
      return {
        ...state,
        isSuccess: false,
        isStreaming: false,
        error: action.payload,
      }
    case 'SET_PARTIAL':
      return {
        ...state,
        isStreaming: true,
        streamData: action.payload,
      }
    case 'SET_FINAL':
      return {
        ...state,
        isSuccess: true,
        isStreaming: false,
        finalData: action.payload,
      }
    case 'RESET':
      return {
        isSuccess: false,
        isStreaming: false,
        error: undefined,
        finalData: undefined,
        streamData: undefined,
      }
    default:
      return state
  }
}

/**
 * Base hook for executing BAML server actions, supporting both streaming and non‑streaming modes.
 *
 * This hook provides a unified interface for handling loading states, partial updates, errors,
 * and final responses. It is designed to be used directly with any BAML server action.
 *
 * Features:
 * - **Streaming Support:** Real‑time partial updates via `streamData`, progress indicators, and incremental UI updates.
 * - **State Management:** Manages loading state (`isLoading`), success/error flags, and final/partial results.
 * - **Error Handling:** Supports type‑safe error handling for BamlValidationError, BamlClientFinishReasonError, and standard errors.
 *
 * @param Action - The server action to invoke.
 * @param props - Configuration props for the hook.
 * @returns An object with the current state and a `mutate` function to trigger the action.
 *
 * @example
 * ```tsx
 * const { data, error, isLoading, mutate } = useBamlAction(StreamingActions.TestAws, { stream: true });
 * ```
 */
function useBamlAction<FunctionName extends FunctionNames>(
  action: ServerAction,
  props: HookInput<FunctionName, { stream: false }>,
): HookOutput<FunctionName, { stream: false }>
function useBamlAction<FunctionName extends FunctionNames>(
  action: ServerAction,
  props?: HookInput<FunctionName, { stream?: true }>,
): HookOutput<FunctionName, { stream: true }>
function useBamlAction<FunctionName extends FunctionNames>(
  action: ServerAction,
  props: HookInput<FunctionName, { stream?: boolean }> = {},
): HookOutput<FunctionName, { stream: true }> | HookOutput<FunctionName, { stream: false }> {
  const { onFinalData, onError } = props
  const [isLoading, startTransition] = useTransition()

  const [state, dispatch] = useReducer(hookReducer<StreamDataType<FunctionName>, FinalDataType<FunctionName>>, {
    isSuccess: false,
    error: undefined,
    finalData: undefined,
    isStreaming: false,
    streamData: undefined,
  })

  const mutate = useCallback(
    async (...input: Parameters<ServerAction>) => {
      dispatch({ type: 'START_REQUEST' })
      try {
        let response: Awaited<ReturnType<ServerAction>>
        startTransition(async () => {
          // Transform any BamlImage or BamlAudio inputs to their JSON representation
          const transformedInput = input.map(arg => {
            // Check if the argument is an instance of BamlImage or BamlAudio
            // We check the constructor name since the actual classes might be proxied in browser environments
            if (arg && typeof arg === 'object' &&
                (arg.constructor.name === 'BamlImage' || arg.constructor.name === 'BamlAudio')) {
              return arg.toJSON();
            }
            return arg;
          });

          response = await action(...transformedInput)

          if (isStreamingProps(props) && response instanceof ReadableStream) {
            const reader = response.getReader()
            const decoder = new TextDecoder()
            try {
              while (true) {
                const { value, done } = await reader.read()
                if (done) break
                if (value) {
                  const chunk = decoder.decode(value, { stream: true }).trim()
                  try {
                    const parsed: BamlStreamResponse<
                      StreamDataType<FunctionName>,
                      FinalDataType<FunctionName>
                    > = JSON.parse(chunk)
                    if (parsed.error) {
                       if (parsed.error instanceof Error) {
                        throw parsed.error
                      }

                      const parsedError = JSON.parse(parsed.error)
                      const finalError = toBamlError(parsedError)
                      throw finalError
                    }
                    if (parsed.partial !== undefined) {
                      dispatch({ type: 'SET_PARTIAL', payload: parsed.partial })
                      if (isStreamingProps(props)) {
                        props.onStreamData?.(parsed.partial)
                      }
                      props.onData?.(parsed.partial)
                    }
                    if (parsed.final !== undefined) {
                      dispatch({ type: 'SET_FINAL', payload: parsed.final })
                      onFinalData?.(parsed.final)
                      props.onData?.(parsed.final)
                      return
                    }
                  } catch (err: unknown) {
                    dispatch({
                      type: 'SET_ERROR',
                      payload: err as BamlErrors,
                    })
                    onError?.(err as BamlErrors)
                    break
                  }
                }
              }
            } finally {
              reader.releaseLock()
            }
            return
          }
          // Non‑streaming case
          dispatch({ type: 'SET_FINAL', payload: response })
          onFinalData?.(response)
        })
        return response
      } catch (error_: unknown) {
        dispatch({ type: 'SET_ERROR', payload: error_ as BamlErrors })
        onError?.(error_ as BamlErrors)
        throw error_
      }
    },
    [action, onFinalData, onError, props],
  )

  const status = useMemo<HookStatus<{ stream: typeof props.stream }>>(() => {
    if (state.error) return 'error'
    if (state.isSuccess) return 'success'
    if (state.isStreaming) return 'streaming'
    if (isLoading) return 'pending'
    return 'idle'
  }, [isLoading, state.error, state.isSuccess, state.isStreaming])

  let data:
		| FinalDataType<FunctionName>
		| StreamDataType<FunctionName>
		| undefined = state.finalData;
  if (state.isStreaming) data = state.streamData

  const result = {
    data,
    finalData: state.finalData,
    error: state.error,
    isError: status === 'error',
    isSuccess: status === 'success',
    isStreaming: status === 'streaming',
    isPending: status === 'pending',
    isLoading: status === 'pending' || status === 'streaming',
    mutate,
    status,
    reset: () => dispatch({ type: 'RESET' }),
  } satisfies HookOutput<FunctionName, { stream: typeof props.stream }>

  return {
    ...result,
    streamData: isStreamingProps(props) ? state.streamData : undefined,
  } satisfies HookOutput<FunctionName, { stream: typeof props.stream }>
}
/**
 * A specialized hook for the AppointmentNudge BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - type: string
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.AppointmentNudgeOutput
 * - **Streaming Partial:** AppointmentNudgeOutput
 * - **Streaming Final:** types.AppointmentNudgeOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = useAppointmentNudge({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = useAppointmentNudge({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useAppointmentNudge(props: HookInput<'AppointmentNudge', { stream: false }>): HookOutput<'AppointmentNudge', { stream: false }>
export function useAppointmentNudge(props?: HookInput<'AppointmentNudge', { stream?: true }>): HookOutput<'AppointmentNudge', { stream: true }>
export function useAppointmentNudge(
  props: HookInput<'AppointmentNudge', { stream?: boolean }> = {},
): HookOutput<'AppointmentNudge', { stream: true }> | HookOutput<'AppointmentNudge', { stream: false }> {
  let action: ServerAction = Actions.AppointmentNudge;
  if (isStreamingProps(props)) {
    action = StreamingActions.AppointmentNudge;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'AppointmentNudge', { stream: false }>)
  }
}
/**
 * A specialized hook for the BabyVisitExplainer BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - ageWeeks: number
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.BabyVisitExplainerOutput
 * - **Streaming Partial:** BabyVisitExplainerOutput
 * - **Streaming Final:** types.BabyVisitExplainerOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = useBabyVisitExplainer({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = useBabyVisitExplainer({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useBabyVisitExplainer(props: HookInput<'BabyVisitExplainer', { stream: false }>): HookOutput<'BabyVisitExplainer', { stream: false }>
export function useBabyVisitExplainer(props?: HookInput<'BabyVisitExplainer', { stream?: true }>): HookOutput<'BabyVisitExplainer', { stream: true }>
export function useBabyVisitExplainer(
  props: HookInput<'BabyVisitExplainer', { stream?: boolean }> = {},
): HookOutput<'BabyVisitExplainer', { stream: true }> | HookOutput<'BabyVisitExplainer', { stream: false }> {
  let action: ServerAction = Actions.BabyVisitExplainer;
  if (isStreamingProps(props)) {
    action = StreamingActions.BabyVisitExplainer;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'BabyVisitExplainer', { stream: false }>)
  }
}
/**
 * A specialized hook for the BirthPlanHeadline BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - mode: string
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.BirthPlanHeadlineOutput
 * - **Streaming Partial:** BirthPlanHeadlineOutput
 * - **Streaming Final:** types.BirthPlanHeadlineOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = useBirthPlanHeadline({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = useBirthPlanHeadline({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useBirthPlanHeadline(props: HookInput<'BirthPlanHeadline', { stream: false }>): HookOutput<'BirthPlanHeadline', { stream: false }>
export function useBirthPlanHeadline(props?: HookInput<'BirthPlanHeadline', { stream?: true }>): HookOutput<'BirthPlanHeadline', { stream: true }>
export function useBirthPlanHeadline(
  props: HookInput<'BirthPlanHeadline', { stream?: boolean }> = {},
): HookOutput<'BirthPlanHeadline', { stream: true }> | HookOutput<'BirthPlanHeadline', { stream: false }> {
  let action: ServerAction = Actions.BirthPlanHeadline;
  if (isStreamingProps(props)) {
    action = StreamingActions.BirthPlanHeadline;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'BirthPlanHeadline', { stream: false }>)
  }
}
/**
 * A specialized hook for the HospitalPackAdvice BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - progress: number
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.HospitalPackAdviceOutput
 * - **Streaming Partial:** HospitalPackAdviceOutput
 * - **Streaming Final:** types.HospitalPackAdviceOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = useHospitalPackAdvice({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = useHospitalPackAdvice({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useHospitalPackAdvice(props: HookInput<'HospitalPackAdvice', { stream: false }>): HookOutput<'HospitalPackAdvice', { stream: false }>
export function useHospitalPackAdvice(props?: HookInput<'HospitalPackAdvice', { stream?: true }>): HookOutput<'HospitalPackAdvice', { stream: true }>
export function useHospitalPackAdvice(
  props: HookInput<'HospitalPackAdvice', { stream?: boolean }> = {},
): HookOutput<'HospitalPackAdvice', { stream: true }> | HookOutput<'HospitalPackAdvice', { stream: false }> {
  let action: ServerAction = Actions.HospitalPackAdvice;
  if (isStreamingProps(props)) {
    action = StreamingActions.HospitalPackAdvice;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'HospitalPackAdvice', { stream: false }>)
  }
}
/**
 * A specialized hook for the NewbornWeekMilestone BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - week: number
 *
 * - babySex (optional): string | null
 *
 * - firstPregnancy: boolean
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.NewbornMilestoneOutput
 * - **Streaming Partial:** NewbornMilestoneOutput
 * - **Streaming Final:** types.NewbornMilestoneOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = useNewbornWeekMilestone({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = useNewbornWeekMilestone({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useNewbornWeekMilestone(props: HookInput<'NewbornWeekMilestone', { stream: false }>): HookOutput<'NewbornWeekMilestone', { stream: false }>
export function useNewbornWeekMilestone(props?: HookInput<'NewbornWeekMilestone', { stream?: true }>): HookOutput<'NewbornWeekMilestone', { stream: true }>
export function useNewbornWeekMilestone(
  props: HookInput<'NewbornWeekMilestone', { stream?: boolean }> = {},
): HookOutput<'NewbornWeekMilestone', { stream: true }> | HookOutput<'NewbornWeekMilestone', { stream: false }> {
  let action: ServerAction = Actions.NewbornWeekMilestone;
  if (isStreamingProps(props)) {
    action = StreamingActions.NewbornWeekMilestone;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'NewbornWeekMilestone', { stream: false }>)
  }
}
/**
 * A specialized hook for the PostpartumTips BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - day: number
 *
 * - firstPregnancy: boolean
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.PostpartumTipsOutput
 * - **Streaming Partial:** PostpartumTipsOutput
 * - **Streaming Final:** types.PostpartumTipsOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = usePostpartumTips({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = usePostpartumTips({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function usePostpartumTips(props: HookInput<'PostpartumTips', { stream: false }>): HookOutput<'PostpartumTips', { stream: false }>
export function usePostpartumTips(props?: HookInput<'PostpartumTips', { stream?: true }>): HookOutput<'PostpartumTips', { stream: true }>
export function usePostpartumTips(
  props: HookInput<'PostpartumTips', { stream?: boolean }> = {},
): HookOutput<'PostpartumTips', { stream: true }> | HookOutput<'PostpartumTips', { stream: false }> {
  let action: ServerAction = Actions.PostpartumTips;
  if (isStreamingProps(props)) {
    action = StreamingActions.PostpartumTips;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'PostpartumTips', { stream: false }>)
  }
}
/**
 * A specialized hook for the PregnancyWeekSummary BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - week: number
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.PregnancyWeekSummaryOutput
 * - **Streaming Partial:** PregnancyWeekSummaryOutput
 * - **Streaming Final:** types.PregnancyWeekSummaryOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = usePregnancyWeekSummary({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = usePregnancyWeekSummary({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function usePregnancyWeekSummary(props: HookInput<'PregnancyWeekSummary', { stream: false }>): HookOutput<'PregnancyWeekSummary', { stream: false }>
export function usePregnancyWeekSummary(props?: HookInput<'PregnancyWeekSummary', { stream?: true }>): HookOutput<'PregnancyWeekSummary', { stream: true }>
export function usePregnancyWeekSummary(
  props: HookInput<'PregnancyWeekSummary', { stream?: boolean }> = {},
): HookOutput<'PregnancyWeekSummary', { stream: true }> | HookOutput<'PregnancyWeekSummary', { stream: false }> {
  let action: ServerAction = Actions.PregnancyWeekSummary;
  if (isStreamingProps(props)) {
    action = StreamingActions.PregnancyWeekSummary;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'PregnancyWeekSummary', { stream: false }>)
  }
}
/**
 * A specialized hook for the SleepRegressionTips BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - week: number
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.SleepRegressionTipsOutput
 * - **Streaming Partial:** SleepRegressionTipsOutput
 * - **Streaming Final:** types.SleepRegressionTipsOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = useSleepRegressionTips({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = useSleepRegressionTips({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useSleepRegressionTips(props: HookInput<'SleepRegressionTips', { stream: false }>): HookOutput<'SleepRegressionTips', { stream: false }>
export function useSleepRegressionTips(props?: HookInput<'SleepRegressionTips', { stream?: true }>): HookOutput<'SleepRegressionTips', { stream: true }>
export function useSleepRegressionTips(
  props: HookInput<'SleepRegressionTips', { stream?: boolean }> = {},
): HookOutput<'SleepRegressionTips', { stream: true }> | HookOutput<'SleepRegressionTips', { stream: false }> {
  let action: ServerAction = Actions.SleepRegressionTips;
  if (isStreamingProps(props)) {
    action = StreamingActions.SleepRegressionTips;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'SleepRegressionTips', { stream: false }>)
  }
}
/**
 * A specialized hook for the StalePrompts BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - topic: string
 *
 * - context: Record<string, string>
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.StalePromptsOutput
 * - **Streaming Partial:** StalePromptsOutput
 * - **Streaming Final:** types.StalePromptsOutput
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = useStalePrompts({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = useStalePrompts({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useStalePrompts(props: HookInput<'StalePrompts', { stream: false }>): HookOutput<'StalePrompts', { stream: false }>
export function useStalePrompts(props?: HookInput<'StalePrompts', { stream?: true }>): HookOutput<'StalePrompts', { stream: true }>
export function useStalePrompts(
  props: HookInput<'StalePrompts', { stream?: boolean }> = {},
): HookOutput<'StalePrompts', { stream: true }> | HookOutput<'StalePrompts', { stream: false }> {
  let action: ServerAction = Actions.StalePrompts;
  if (isStreamingProps(props)) {
    action = StreamingActions.StalePrompts;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'StalePrompts', { stream: false }>)
  }
}
/**
 * A specialized hook for the SuggestImprovements BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - seo: string
 *
 * - accessibility: string
 *
 * - structure: string
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** types.ImprovementSuggestions
 * - **Streaming Partial:** ImprovementSuggestions
 * - **Streaming Final:** types.ImprovementSuggestions
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isLoading, mutate } = useSuggestImprovements({ stream: false});
 *
 * // Streaming usage:
 * const { data, streamData, isLoading, error, mutate } = useSuggestImprovements({
 *   stream: true | undefined,
 *   onStreamData: (partial) => console.log('Partial update:', partial),
 *   onFinalData: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useSuggestImprovements(props: HookInput<'SuggestImprovements', { stream: false }>): HookOutput<'SuggestImprovements', { stream: false }>
export function useSuggestImprovements(props?: HookInput<'SuggestImprovements', { stream?: true }>): HookOutput<'SuggestImprovements', { stream: true }>
export function useSuggestImprovements(
  props: HookInput<'SuggestImprovements', { stream?: boolean }> = {},
): HookOutput<'SuggestImprovements', { stream: true }> | HookOutput<'SuggestImprovements', { stream: false }> {
  let action: ServerAction = Actions.SuggestImprovements;
  if (isStreamingProps(props)) {
    action = StreamingActions.SuggestImprovements;
    return useBamlAction(action, props)
  } else {
    return useBamlAction(action, props as HookInput<'SuggestImprovements', { stream: false }>)
  }
}