/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  AppointmentNudgeOutput,  BabyVisitExplainerOutput,  BirthPlanHeadlineOutput,  HospitalPackAdviceOutput,  ImprovementSuggestions,  NewbornMilestoneOutput,  PostpartumTipsOutput,  PregnancyWeekSummaryOutput,  SleepRegressionTipsOutput,  StalePromptsOutput } from "../types"

import type * as types from "../types"
import type { partial_types }from "../partial_types";

export type StreamingServerTypes = {
  AppointmentNudge: AppointmentNudgeOutput,
  BabyVisitExplainer: BabyVisitExplainerOutput,
  BirthPlanHeadline: BirthPlanHeadlineOutput,
  HospitalPackAdvice: HospitalPackAdviceOutput,
  NewbornWeekMilestone: NewbornMilestoneOutput,
  PostpartumTips: PostpartumTipsOutput,
  PregnancyWeekSummary: PregnancyWeekSummaryOutput,
  SleepRegressionTips: SleepRegressionTipsOutput,
  StalePrompts: StalePromptsOutput,
  SuggestImprovements: ImprovementSuggestions,
}