/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  AppointmentNudgeOutput,  BabyAssistantChatOutput,  BabyContext,  BabyVisitExplainerOutput,  BirthPlanHeadlineOutput,  ChatMessage,  ChatTitleOutput,  CheckInQuestion,  ContextualMilestonesOutput,  DailyCheckInQuestionsOutput,  DailyLearningOutput,  HospitalPackAdviceOutput,  ImprovementSuggestions,  LearningTip,  MilestoneEnhancementOutput,  MilestoneExplanationOutput,  MilestoneSuggestion,  NewbornMilestoneOutput,  ParentTask,  ParentTip,  PersonalizedTasksOutput,  PostpartumTipsInput,  PostpartumTipsOutput,  PregnancyWeekSummaryOutput,  ResponseType,  RoleSpecificTipsOutput,  SleepRegressionTipsOutput,  StalePromptsOutput,  WellnessQuestion,  WellnessScreeningOutput } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "AppointmentNudge" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } type - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AppointmentNudge = async (
  type: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AppointmentNudge(
    type,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "BabyAssistantChat" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { types.ChatMessage[] } conversationHistory - Input parameter.
 * @param { types.BabyContext } babyContext - Input parameter.
 * @param { string } userQuestion - Input parameter.
 * @param { string | null } systemPrompt (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const BabyAssistantChat = async (
  conversationHistory: types.ChatMessage[],
  babyContext: types.BabyContext,
  userQuestion: string,
  systemPrompt?: string | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.BabyAssistantChat(
    conversationHistory,
    babyContext,
    userQuestion,
    systemPrompt,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "BabyVisitExplainer" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number } ageWeeks - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const BabyVisitExplainer = async (
  ageWeeks: number,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.BabyVisitExplainer(
    ageWeeks,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "BirthPlanHeadline" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } mode - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const BirthPlanHeadline = async (
  mode: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.BirthPlanHeadline(
    mode,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "DailyCheckInQuestions" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number } ppDay - Input parameter.
 * @param { string } parentRole - Input parameter.
 * @param { number | null } parentSleepHours (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number } ageInWeeks - Input parameter.
 * @param { boolean } firstPregnancy - Input parameter.
 * @param { number | null } avgFeedingsPerDay (optional) - Input parameter.
 * @param { number | null } avgSleepHoursPerDay (optional) - Input parameter.
 * @param { number | null } avgDiaperChangesPerDay (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const DailyCheckInQuestions = async (
  ppDay: number,
  parentRole: string,
  parentSleepHours?: number | null,
  ageInDays: number,
  ageInWeeks: number,
  firstPregnancy: boolean,
  avgFeedingsPerDay?: number | null,
  avgSleepHoursPerDay?: number | null,
  avgDiaperChangesPerDay?: number | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.DailyCheckInQuestions(
    ppDay,
    parentRole,
    parentSleepHours,
    ageInDays,
    ageInWeeks,
    firstPregnancy,
    avgFeedingsPerDay,
    avgSleepHoursPerDay,
    avgDiaperChangesPerDay,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "DailyLearningContent" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number } postpartumDay - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { boolean } firstTimeParent - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { string | null } parentWellness (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const DailyLearningContent = async (
  postpartumDay: number,
  babyName: string,
  babySex?: string | null,
  firstTimeParent: boolean,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  activitySummary?: string | null,
  parentWellness?: string | null,
  medicalContext?: string | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.DailyLearningContent(
    postpartumDay,
    babyName,
    babySex,
    firstTimeParent,
    recentChatTopics,
    achievedMilestones,
    activitySummary,
    parentWellness,
    medicalContext,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "EnhanceMilestone" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } milestoneTitle - Input parameter.
 * @param { string } milestoneDescription - Input parameter.
 * @param { string } milestoneType - Input parameter.
 * @param { string } ageLabel - Input parameter.
 * @param { string | null } babyName (optional) - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number | null } ageInDays (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { string | null } parentWellness (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const EnhanceMilestone = async (
  milestoneTitle: string,
  milestoneDescription: string,
  milestoneType: string,
  ageLabel: string,
  babyName?: string | null,
  babySex?: string | null,
  ageInDays?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  activitySummary?: string | null,
  parentWellness?: string | null,
  medicalContext?: string | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.EnhanceMilestone(
    milestoneTitle,
    milestoneDescription,
    milestoneType,
    ageLabel,
    babyName,
    babySex,
    ageInDays,
    recentChatTopics,
    achievedMilestones,
    activitySummary,
    parentWellness,
    medicalContext,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "GenerateChatTitle" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } firstUserMessage - Input parameter.
 * @param { string } firstAssistantResponse - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GenerateChatTitle = async (
  firstUserMessage: string,
  firstAssistantResponse: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.GenerateChatTitle(
    firstUserMessage,
    firstAssistantResponse,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "GenerateContextualMilestones" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } babyName - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number } ageInWeeks - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } height (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } totalSleepHours24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingsPerDay (optional) - Input parameter.
 * @param { number | null } avgSleepHoursPerDay (optional) - Input parameter.
 * @param { number | null } avgDiaperChangesPerDay (optional) - Input parameter.
 * @param { string | null } recentDiaperColors (optional) - Input parameter.
 * @param { boolean | null } hasTummyTimeActivity (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GenerateContextualMilestones = async (
  babyName: string,
  ageInDays: number,
  ageInWeeks: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  height?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  totalSleepHours24h?: number | null,
  diaperCount24h?: number | null,
  avgFeedingsPerDay?: number | null,
  avgSleepHoursPerDay?: number | null,
  avgDiaperChangesPerDay?: number | null,
  recentDiaperColors?: string | null,
  hasTummyTimeActivity?: boolean | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.GenerateContextualMilestones(
    babyName,
    ageInDays,
    ageInWeeks,
    currentWeightOz,
    birthWeightOz,
    height,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    totalSleepHours24h,
    diaperCount24h,
    avgFeedingsPerDay,
    avgSleepHoursPerDay,
    avgDiaperChangesPerDay,
    recentDiaperColors,
    hasTummyTimeActivity,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "HospitalPackAdvice" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number } progress - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const HospitalPackAdvice = async (
  progress: number,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.HospitalPackAdvice(
    progress,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "MilestoneExplanation" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } milestoneTitle - Input parameter.
 * @param { string } milestoneType - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number } ageInWeeks - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const MilestoneExplanation = async (
  milestoneTitle: string,
  milestoneType: string,
  babyName: string,
  ageInDays: number,
  ageInWeeks: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.MilestoneExplanation(
    milestoneTitle,
    milestoneType,
    babyName,
    ageInDays,
    ageInWeeks,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    sleepCount24h,
    diaperCount24h,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "NewbornWeekMilestone" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } babyName - Input parameter.
 * @param { number } week - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { boolean } firstPregnancy - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } height (optional) - Input parameter.
 * @param { number | null } headCircumference (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { string | null } parentWellness (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const NewbornWeekMilestone = async (
  babyName: string,
  week: number,
  babySex?: string | null,
  firstPregnancy: boolean,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  height?: number | null,
  headCircumference?: number | null,
  feedingCount24h?: number | null,
  sleepCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  activitySummary?: string | null,
  parentWellness?: string | null,
  medicalContext?: string | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.NewbornWeekMilestone(
    babyName,
    week,
    babySex,
    firstPregnancy,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    height,
    headCircumference,
    feedingCount24h,
    sleepCount24h,
    recentChatTopics,
    achievedMilestones,
    activitySummary,
    parentWellness,
    medicalContext,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "PersonalizedTasks" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number } babyAgeInDays - Input parameter.
 * @param { number } ppWeek - Input parameter.
 * @param { string } timeOfDay - Input parameter.
 * @param { string } feedingMethod - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const PersonalizedTasks = async (
  babyAgeInDays: number,
  ppWeek: number,
  timeOfDay: string,
  feedingMethod: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.PersonalizedTasks(
    babyAgeInDays,
    ppWeek,
    timeOfDay,
    feedingMethod,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "PostpartumTips" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { types.PostpartumTipsInput } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const PostpartumTips = async (
  input: types.PostpartumTipsInput,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.PostpartumTips(
    input,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "PregnancyWeekSummary" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number } week - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const PregnancyWeekSummary = async (
  week: number,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.PregnancyWeekSummary(
    week,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "RoleSpecificTips" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } parentRole - Input parameter.
 * @param { number | null } ppDay (optional) - Input parameter.
 * @param { number } babyAgeInDays - Input parameter.
 * @param { string | null } babyName (optional) - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { string } topic - Input parameter.
 * @param { number | null } recentSleepHours (optional) - Input parameter.
 * @param { string[] | null } concerns (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { string | null } parentWellness (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const RoleSpecificTips = async (
  parentRole: string,
  ppDay?: number | null,
  babyAgeInDays: number,
  babyName?: string | null,
  babySex?: string | null,
  topic: string,
  recentSleepHours?: number | null,
  concerns?: string[] | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  activitySummary?: string | null,
  parentWellness?: string | null,
  medicalContext?: string | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.RoleSpecificTips(
    parentRole,
    ppDay,
    babyAgeInDays,
    babyName,
    babySex,
    topic,
    recentSleepHours,
    concerns,
    recentChatTopics,
    achievedMilestones,
    activitySummary,
    parentWellness,
    medicalContext,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "SleepRegressionTips" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } babyName - Input parameter.
 * @param { number } week - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } totalSleepHours24h (optional) - Input parameter.
 * @param { number | null } avgSleepHoursPerDay (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const SleepRegressionTips = async (
  babyName: string,
  week: number,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  sleepCount24h?: number | null,
  totalSleepHours24h?: number | null,
  avgSleepHoursPerDay?: number | null,
  feedingCount24h?: number | null,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.SleepRegressionTips(
    babyName,
    week,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    sleepCount24h,
    totalSleepHours24h,
    avgSleepHoursPerDay,
    feedingCount24h,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "StalePrompts" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } topic - Input parameter.
 * @param { Record<string, string> } context - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const StalePrompts = async (
  topic: string,
  context: Record<string, string>,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.StalePrompts(
    topic,
    context,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "SuggestImprovements" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } seo - Input parameter.
 * @param { string } accessibility - Input parameter.
 * @param { string } structure - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const SuggestImprovements = async (
  seo: string,
  accessibility: string,
  structure: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.SuggestImprovements(
    seo,
    accessibility,
    structure,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "WellnessScreening" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number } ppDay - Input parameter.
 * @param { number | null } ppWeek (optional) - Input parameter.
 * @param { boolean } firstPregnancy - Input parameter.
 * @param { string } babyFirstName - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { string } previousCheckIns - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const WellnessScreening = async (
  ppDay: number,
  ppWeek?: number | null,
  firstPregnancy: boolean,
  babyFirstName: string,
  ageInDays: number,
  previousCheckIns: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.WellnessScreening(
    ppDay,
    ppWeek,
    firstPregnancy,
    babyFirstName,
    ageInDays,
    previousCheckIns,
  );
  return Promise.resolve(stream.toStreamable());
};