/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  AppointmentNudgeOutput,  BabyAssistantChatOutput,  BabyContext,  BabyVisitExplainerOutput,  BirthPlanHeadlineOutput,  ChatMessage,  ChatTitleOutput,  CheckInQuestion,  ContextualMilestonesOutput,  DailyCheckInQuestionsOutput,  HospitalPackAdviceOutput,  ImprovementSuggestions,  LearningTip,  MilestoneExplanationOutput,  MilestoneSuggestion,  NewbornMilestoneOutput,  ParentTask,  ParentTip,  PersonalizedTasksOutput,  PostpartumTipsOutput,  PregnancyWeekSummaryOutput,  ResponseType,  RoleSpecificTipsOutput,  SleepRegressionTipsOutput,  StalePromptsOutput,  WellnessQuestion,  WellnessScreeningOutput } from "../types"

import type * as types from "../types"
import type { partial_types }from "../partial_types";

export type StreamingServerTypes = {
  AppointmentNudge: AppointmentNudgeOutput,
  BabyAssistantChat: BabyAssistantChatOutput,
  BabyVisitExplainer: BabyVisitExplainerOutput,
  BirthPlanHeadline: BirthPlanHeadlineOutput,
  DailyCheckInQuestions: DailyCheckInQuestionsOutput,
  GenerateChatTitle: ChatTitleOutput,
  GenerateContextualMilestones: ContextualMilestonesOutput,
  HospitalPackAdvice: HospitalPackAdviceOutput,
  MilestoneExplanation: MilestoneExplanationOutput,
  NewbornWeekMilestone: NewbornMilestoneOutput,
  PersonalizedTasks: PersonalizedTasksOutput,
  PostpartumTips: PostpartumTipsOutput,
  PregnancyWeekSummary: PregnancyWeekSummaryOutput,
  RoleSpecificTips: RoleSpecificTipsOutput,
  SleepRegressionTips: SleepRegressionTipsOutput,
  StalePrompts: StalePromptsOutput,
  SuggestImprovements: ImprovementSuggestions,
  WellnessScreening: WellnessScreeningOutput,
}