/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  AppointmentNudgeOutput,  BabyAssistantChatOutput,  BabyContext,  BabyVisitExplainerOutput,  BirthPlanHeadlineOutput,  ChatMessage,  ChatTitleOutput,  CheckInQuestion,  ContextualMilestonesOutput,  DailyCheckInQuestionsOutput,  DailyLearningPlan,  HospitalPackAdviceOutput,  ImprovementSuggestions,  LearningPlanItem,  LearningTip,  MilestoneEnhancementOutput,  MilestoneExplanationOutput,  MilestoneInput,  MilestonePlan,  MilestonePlanItem,  MilestoneSuggestion,  NewbornMilestoneOutput,  ParentTask,  ParentTip,  PersonalizedTasksOutput,  PostpartumTipsInput,  PostpartumTipsOutput,  PregnancyWeekSummaryOutput,  ResponseType,  RoleSpecificTipsOutput,  SleepRegressionTipsOutput,  StalePromptsOutput,  WellnessQuestion,  WellnessScreeningOutput } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "AppointmentNudge" BAML action.
 *
 * This server action calls the underlying BAML function "AppointmentNudge"
 * with the specified parameters.
 *
 * @param { string } type - Input parameter.
 *
 * @returns {Promise<types.AppointmentNudgeOutput>} A promise that resolves with the result of the action.
 */
export const AppointmentNudge = async (
  type: string,
): Promise<types.AppointmentNudgeOutput> => {
  return b.AppointmentNudge(
    type,
  );
};

/**
 * Executes the "BabyAssistantChat" BAML action.
 *
 * This server action calls the underlying BAML function "BabyAssistantChat"
 * with the specified parameters.
 *
 * @param { types.ChatMessage[] } conversationHistory - Input parameter.
 * @param { types.BabyContext } babyContext - Input parameter.
 * @param { string } userQuestion - Input parameter.
 * @param { string | null } systemPrompt (optional) - Input parameter.
 *
 * @returns {Promise<types.BabyAssistantChatOutput>} A promise that resolves with the result of the action.
 */
export const BabyAssistantChat = async (
  conversationHistory: types.ChatMessage[],
  babyContext: types.BabyContext,
  userQuestion: string,
  systemPrompt?: string | null,
): Promise<types.BabyAssistantChatOutput> => {
  return b.BabyAssistantChat(
    conversationHistory,
    babyContext,
    userQuestion,
    systemPrompt,
  );
};

/**
 * Executes the "BabyVisitExplainer" BAML action.
 *
 * This server action calls the underlying BAML function "BabyVisitExplainer"
 * with the specified parameters.
 *
 * @param { number } ageWeeks - Input parameter.
 *
 * @returns {Promise<types.BabyVisitExplainerOutput>} A promise that resolves with the result of the action.
 */
export const BabyVisitExplainer = async (
  ageWeeks: number,
): Promise<types.BabyVisitExplainerOutput> => {
  return b.BabyVisitExplainer(
    ageWeeks,
  );
};

/**
 * Executes the "BirthPlanHeadline" BAML action.
 *
 * This server action calls the underlying BAML function "BirthPlanHeadline"
 * with the specified parameters.
 *
 * @param { string } mode - Input parameter.
 *
 * @returns {Promise<types.BirthPlanHeadlineOutput>} A promise that resolves with the result of the action.
 */
export const BirthPlanHeadline = async (
  mode: string,
): Promise<types.BirthPlanHeadlineOutput> => {
  return b.BirthPlanHeadline(
    mode,
  );
};

/**
 * Executes the "DailyCheckInQuestions" BAML action.
 *
 * This server action calls the underlying BAML function "DailyCheckInQuestions"
 * with the specified parameters.
 *
 * @param { number } ppDay - Input parameter.
 * @param { string } parentRole - Input parameter.
 * @param { number | null } parentSleepHours (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number } ageInWeeks - Input parameter.
 * @param { boolean } firstPregnancy - Input parameter.
 * @param { number | null } avgFeedingsPerDay (optional) - Input parameter.
 * @param { number | null } avgSleepHoursPerDay (optional) - Input parameter.
 * @param { number | null } avgDiaperChangesPerDay (optional) - Input parameter.
 *
 * @returns {Promise<types.DailyCheckInQuestionsOutput>} A promise that resolves with the result of the action.
 */
export const DailyCheckInQuestions = async (
  ppDay: number,
  parentRole: string,
  parentSleepHours?: number | null,
  ageInDays: number,
  ageInWeeks: number,
  firstPregnancy: boolean,
  avgFeedingsPerDay?: number | null,
  avgSleepHoursPerDay?: number | null,
  avgDiaperChangesPerDay?: number | null,
): Promise<types.DailyCheckInQuestionsOutput> => {
  return b.DailyCheckInQuestions(
    ppDay,
    parentRole,
    parentSleepHours,
    ageInDays,
    ageInWeeks,
    firstPregnancy,
    avgFeedingsPerDay,
    avgSleepHoursPerDay,
    avgDiaperChangesPerDay,
  );
};

/**
 * Executes the "DailyLearningPlanner" BAML action.
 *
 * This server action calls the underlying BAML function "DailyLearningPlanner"
 * with the specified parameters.
 *
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number } ageInWeeks - Input parameter.
 * @param { boolean } firstTimeParent - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } height (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } totalSleepHours24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingsPerDay (optional) - Input parameter.
 * @param { number | null } avgSleepHoursPerDay (optional) - Input parameter.
 * @param { number | null } avgDiaperChangesPerDay (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } recentlyCoveredTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { string | null } parentWellness (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.DailyLearningPlan>} A promise that resolves with the result of the action.
 */
export const DailyLearningPlanner = async (
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  ageInWeeks: number,
  firstTimeParent: boolean,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  height?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  totalSleepHours24h?: number | null,
  diaperCount24h?: number | null,
  avgFeedingsPerDay?: number | null,
  avgSleepHoursPerDay?: number | null,
  avgDiaperChangesPerDay?: number | null,
  recentChatTopics?: string | null,
  recentlyCoveredTopics?: string | null,
  achievedMilestones?: string | null,
  activitySummary?: string | null,
  parentWellness?: string | null,
  medicalContext?: string | null,
): Promise<types.DailyLearningPlan> => {
  return b.DailyLearningPlanner(
    babyName,
    babySex,
    ageInDays,
    ageInWeeks,
    firstTimeParent,
    currentWeightOz,
    birthWeightOz,
    height,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    totalSleepHours24h,
    diaperCount24h,
    avgFeedingsPerDay,
    avgSleepHoursPerDay,
    avgDiaperChangesPerDay,
    recentChatTopics,
    recentlyCoveredTopics,
    achievedMilestones,
    activitySummary,
    parentWellness,
    medicalContext,
  );
};

/**
 * Executes the "EnhanceMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "EnhanceMilestone"
 * with the specified parameters.
 *
 * @param { string } milestoneTitle - Input parameter.
 * @param { string } milestoneDescription - Input parameter.
 * @param { string } milestoneType - Input parameter.
 * @param { string } ageLabel - Input parameter.
 * @param { string | null } babyName (optional) - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number | null } ageInDays (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { string | null } parentWellness (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.MilestoneEnhancementOutput>} A promise that resolves with the result of the action.
 */
export const EnhanceMilestone = async (
  milestoneTitle: string,
  milestoneDescription: string,
  milestoneType: string,
  ageLabel: string,
  babyName?: string | null,
  babySex?: string | null,
  ageInDays?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  activitySummary?: string | null,
  parentWellness?: string | null,
  medicalContext?: string | null,
): Promise<types.MilestoneEnhancementOutput> => {
  return b.EnhanceMilestone(
    milestoneTitle,
    milestoneDescription,
    milestoneType,
    ageLabel,
    babyName,
    babySex,
    ageInDays,
    recentChatTopics,
    achievedMilestones,
    activitySummary,
    parentWellness,
    medicalContext,
  );
};

/**
 * Executes the "FirstWeekMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "FirstWeekMilestone"
 * with the specified parameters.
 *
 * @param { types.MilestoneInput } input - Input parameter.
 *
 * @returns {Promise<types.MilestoneEnhancementOutput>} A promise that resolves with the result of the action.
 */
export const FirstWeekMilestone = async (
  input: types.MilestoneInput,
): Promise<types.MilestoneEnhancementOutput> => {
  return b.FirstWeekMilestone(
    input,
  );
};

/**
 * Executes the "GenerateChatTitle" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateChatTitle"
 * with the specified parameters.
 *
 * @param { string } firstUserMessage - Input parameter.
 * @param { string } firstAssistantResponse - Input parameter.
 *
 * @returns {Promise<types.ChatTitleOutput>} A promise that resolves with the result of the action.
 */
export const GenerateChatTitle = async (
  firstUserMessage: string,
  firstAssistantResponse: string,
): Promise<types.ChatTitleOutput> => {
  return b.GenerateChatTitle(
    firstUserMessage,
    firstAssistantResponse,
  );
};

/**
 * Executes the "GenerateContextualMilestones" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateContextualMilestones"
 * with the specified parameters.
 *
 * @param { string } babyName - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number } ageInWeeks - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } height (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } totalSleepHours24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingsPerDay (optional) - Input parameter.
 * @param { number | null } avgSleepHoursPerDay (optional) - Input parameter.
 * @param { number | null } avgDiaperChangesPerDay (optional) - Input parameter.
 * @param { string | null } recentDiaperColors (optional) - Input parameter.
 * @param { boolean | null } hasTummyTimeActivity (optional) - Input parameter.
 *
 * @returns {Promise<types.ContextualMilestonesOutput>} A promise that resolves with the result of the action.
 */
export const GenerateContextualMilestones = async (
  babyName: string,
  ageInDays: number,
  ageInWeeks: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  height?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  totalSleepHours24h?: number | null,
  diaperCount24h?: number | null,
  avgFeedingsPerDay?: number | null,
  avgSleepHoursPerDay?: number | null,
  avgDiaperChangesPerDay?: number | null,
  recentDiaperColors?: string | null,
  hasTummyTimeActivity?: boolean | null,
): Promise<types.ContextualMilestonesOutput> => {
  return b.GenerateContextualMilestones(
    babyName,
    ageInDays,
    ageInWeeks,
    currentWeightOz,
    birthWeightOz,
    height,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    totalSleepHours24h,
    diaperCount24h,
    avgFeedingsPerDay,
    avgSleepHoursPerDay,
    avgDiaperChangesPerDay,
    recentDiaperColors,
    hasTummyTimeActivity,
  );
};

/**
 * Executes the "GenerateLearningTip_FirstWeek" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateLearningTip_FirstWeek"
 * with the specified parameters.
 *
 * @param { string } category - Input parameter.
 * @param { string } title - Input parameter.
 * @param { string } subtitle - Input parameter.
 * @param { string } relevance - Input parameter.
 * @param { boolean } recommendYesNo - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.LearningTip>} A promise that resolves with the result of the action.
 */
export const GenerateLearningTip_FirstWeek = async (
  category: string,
  title: string,
  subtitle: string,
  relevance: string,
  recommendYesNo: boolean,
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  medicalContext?: string | null,
): Promise<types.LearningTip> => {
  return b.GenerateLearningTip_FirstWeek(
    category,
    title,
    subtitle,
    relevance,
    recommendYesNo,
    babyName,
    babySex,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    diaperCount24h,
    recentChatTopics,
    achievedMilestones,
    medicalContext,
  );
};

/**
 * Executes the "GenerateLearningTip_ImmediatePostbirth" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateLearningTip_ImmediatePostbirth"
 * with the specified parameters.
 *
 * @param { string } category - Input parameter.
 * @param { string } title - Input parameter.
 * @param { string } subtitle - Input parameter.
 * @param { string } relevance - Input parameter.
 * @param { boolean } recommendYesNo - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.LearningTip>} A promise that resolves with the result of the action.
 */
export const GenerateLearningTip_ImmediatePostbirth = async (
  category: string,
  title: string,
  subtitle: string,
  relevance: string,
  recommendYesNo: boolean,
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  medicalContext?: string | null,
): Promise<types.LearningTip> => {
  return b.GenerateLearningTip_ImmediatePostbirth(
    category,
    title,
    subtitle,
    relevance,
    recommendYesNo,
    babyName,
    babySex,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    diaperCount24h,
    recentChatTopics,
    achievedMilestones,
    medicalContext,
  );
};

/**
 * Executes the "GenerateLearningTip_MonthOne" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateLearningTip_MonthOne"
 * with the specified parameters.
 *
 * @param { string } category - Input parameter.
 * @param { string } title - Input parameter.
 * @param { string } subtitle - Input parameter.
 * @param { string } relevance - Input parameter.
 * @param { boolean } recommendYesNo - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.LearningTip>} A promise that resolves with the result of the action.
 */
export const GenerateLearningTip_MonthOne = async (
  category: string,
  title: string,
  subtitle: string,
  relevance: string,
  recommendYesNo: boolean,
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  medicalContext?: string | null,
): Promise<types.LearningTip> => {
  return b.GenerateLearningTip_MonthOne(
    category,
    title,
    subtitle,
    relevance,
    recommendYesNo,
    babyName,
    babySex,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    diaperCount24h,
    recentChatTopics,
    achievedMilestones,
    medicalContext,
  );
};

/**
 * Executes the "GenerateLearningTip_MonthThreeFour" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateLearningTip_MonthThreeFour"
 * with the specified parameters.
 *
 * @param { string } category - Input parameter.
 * @param { string } title - Input parameter.
 * @param { string } subtitle - Input parameter.
 * @param { string } relevance - Input parameter.
 * @param { boolean } recommendYesNo - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.LearningTip>} A promise that resolves with the result of the action.
 */
export const GenerateLearningTip_MonthThreeFour = async (
  category: string,
  title: string,
  subtitle: string,
  relevance: string,
  recommendYesNo: boolean,
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  medicalContext?: string | null,
): Promise<types.LearningTip> => {
  return b.GenerateLearningTip_MonthThreeFour(
    category,
    title,
    subtitle,
    relevance,
    recommendYesNo,
    babyName,
    babySex,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    diaperCount24h,
    recentChatTopics,
    achievedMilestones,
    medicalContext,
  );
};

/**
 * Executes the "GenerateLearningTip_MonthTwo" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateLearningTip_MonthTwo"
 * with the specified parameters.
 *
 * @param { string } category - Input parameter.
 * @param { string } title - Input parameter.
 * @param { string } subtitle - Input parameter.
 * @param { string } relevance - Input parameter.
 * @param { boolean } recommendYesNo - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.LearningTip>} A promise that resolves with the result of the action.
 */
export const GenerateLearningTip_MonthTwo = async (
  category: string,
  title: string,
  subtitle: string,
  relevance: string,
  recommendYesNo: boolean,
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  medicalContext?: string | null,
): Promise<types.LearningTip> => {
  return b.GenerateLearningTip_MonthTwo(
    category,
    title,
    subtitle,
    relevance,
    recommendYesNo,
    babyName,
    babySex,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    diaperCount24h,
    recentChatTopics,
    achievedMilestones,
    medicalContext,
  );
};

/**
 * Executes the "GenerateLearningTip_SecondWeek" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateLearningTip_SecondWeek"
 * with the specified parameters.
 *
 * @param { string } category - Input parameter.
 * @param { string } title - Input parameter.
 * @param { string } subtitle - Input parameter.
 * @param { string } relevance - Input parameter.
 * @param { boolean } recommendYesNo - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.LearningTip>} A promise that resolves with the result of the action.
 */
export const GenerateLearningTip_SecondWeek = async (
  category: string,
  title: string,
  subtitle: string,
  relevance: string,
  recommendYesNo: boolean,
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  medicalContext?: string | null,
): Promise<types.LearningTip> => {
  return b.GenerateLearningTip_SecondWeek(
    category,
    title,
    subtitle,
    relevance,
    recommendYesNo,
    babyName,
    babySex,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    diaperCount24h,
    recentChatTopics,
    achievedMilestones,
    medicalContext,
  );
};

/**
 * Executes the "GenerateLearningTip_ThirdWeek" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateLearningTip_ThirdWeek"
 * with the specified parameters.
 *
 * @param { string } category - Input parameter.
 * @param { string } title - Input parameter.
 * @param { string } subtitle - Input parameter.
 * @param { string } relevance - Input parameter.
 * @param { boolean } recommendYesNo - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.LearningTip>} A promise that resolves with the result of the action.
 */
export const GenerateLearningTip_ThirdWeek = async (
  category: string,
  title: string,
  subtitle: string,
  relevance: string,
  recommendYesNo: boolean,
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  medicalContext?: string | null,
): Promise<types.LearningTip> => {
  return b.GenerateLearningTip_ThirdWeek(
    category,
    title,
    subtitle,
    relevance,
    recommendYesNo,
    babyName,
    babySex,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    diaperCount24h,
    recentChatTopics,
    achievedMilestones,
    medicalContext,
  );
};

/**
 * Executes the "HospitalPackAdvice" BAML action.
 *
 * This server action calls the underlying BAML function "HospitalPackAdvice"
 * with the specified parameters.
 *
 * @param { number } progress - Input parameter.
 *
 * @returns {Promise<types.HospitalPackAdviceOutput>} A promise that resolves with the result of the action.
 */
export const HospitalPackAdvice = async (
  progress: number,
): Promise<types.HospitalPackAdviceOutput> => {
  return b.HospitalPackAdvice(
    progress,
  );
};

/**
 * Executes the "ImmediatePostbirthMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "ImmediatePostbirthMilestone"
 * with the specified parameters.
 *
 * @param { types.MilestoneInput } input - Input parameter.
 *
 * @returns {Promise<types.MilestoneEnhancementOutput>} A promise that resolves with the result of the action.
 */
export const ImmediatePostbirthMilestone = async (
  input: types.MilestoneInput,
): Promise<types.MilestoneEnhancementOutput> => {
  return b.ImmediatePostbirthMilestone(
    input,
  );
};

/**
 * Executes the "MilestoneExplanation" BAML action.
 *
 * This server action calls the underlying BAML function "MilestoneExplanation"
 * with the specified parameters.
 *
 * @param { string } milestoneTitle - Input parameter.
 * @param { string } milestoneType - Input parameter.
 * @param { string } babyName - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number } ageInWeeks - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 *
 * @returns {Promise<types.MilestoneExplanationOutput>} A promise that resolves with the result of the action.
 */
export const MilestoneExplanation = async (
  milestoneTitle: string,
  milestoneType: string,
  babyName: string,
  ageInDays: number,
  ageInWeeks: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  feedingCount24h?: number | null,
  sleepCount24h?: number | null,
  diaperCount24h?: number | null,
): Promise<types.MilestoneExplanationOutput> => {
  return b.MilestoneExplanation(
    milestoneTitle,
    milestoneType,
    babyName,
    ageInDays,
    ageInWeeks,
    currentWeightOz,
    birthWeightOz,
    feedingCount24h,
    sleepCount24h,
    diaperCount24h,
  );
};

/**
 * Executes the "MilestonePlanner" BAML action.
 *
 * This server action calls the underlying BAML function "MilestonePlanner"
 * with the specified parameters.
 *
 * @param { string } babyName - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number } ageInWeeks - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } height (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingInterval (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } totalSleepHours24h (optional) - Input parameter.
 * @param { number | null } diaperCount24h (optional) - Input parameter.
 * @param { number | null } avgFeedingsPerDay (optional) - Input parameter.
 * @param { number | null } avgSleepHoursPerDay (optional) - Input parameter.
 * @param { number | null } avgDiaperChangesPerDay (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } recentlySuggestedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { boolean | null } hasTummyTimeActivity (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.MilestonePlan>} A promise that resolves with the result of the action.
 */
export const MilestonePlanner = async (
  babyName: string,
  babySex?: string | null,
  ageInDays: number,
  ageInWeeks: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  height?: number | null,
  feedingCount24h?: number | null,
  avgFeedingInterval?: number | null,
  sleepCount24h?: number | null,
  totalSleepHours24h?: number | null,
  diaperCount24h?: number | null,
  avgFeedingsPerDay?: number | null,
  avgSleepHoursPerDay?: number | null,
  avgDiaperChangesPerDay?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  recentlySuggestedMilestones?: string | null,
  activitySummary?: string | null,
  hasTummyTimeActivity?: boolean | null,
  medicalContext?: string | null,
): Promise<types.MilestonePlan> => {
  return b.MilestonePlanner(
    babyName,
    babySex,
    ageInDays,
    ageInWeeks,
    currentWeightOz,
    birthWeightOz,
    height,
    feedingCount24h,
    avgFeedingInterval,
    sleepCount24h,
    totalSleepHours24h,
    diaperCount24h,
    avgFeedingsPerDay,
    avgSleepHoursPerDay,
    avgDiaperChangesPerDay,
    recentChatTopics,
    achievedMilestones,
    recentlySuggestedMilestones,
    activitySummary,
    hasTummyTimeActivity,
    medicalContext,
  );
};

/**
 * Executes the "MonthOneMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "MonthOneMilestone"
 * with the specified parameters.
 *
 * @param { types.MilestoneInput } input - Input parameter.
 *
 * @returns {Promise<types.MilestoneEnhancementOutput>} A promise that resolves with the result of the action.
 */
export const MonthOneMilestone = async (
  input: types.MilestoneInput,
): Promise<types.MilestoneEnhancementOutput> => {
  return b.MonthOneMilestone(
    input,
  );
};

/**
 * Executes the "MonthThreeFourMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "MonthThreeFourMilestone"
 * with the specified parameters.
 *
 * @param { types.MilestoneInput } input - Input parameter.
 *
 * @returns {Promise<types.MilestoneEnhancementOutput>} A promise that resolves with the result of the action.
 */
export const MonthThreeFourMilestone = async (
  input: types.MilestoneInput,
): Promise<types.MilestoneEnhancementOutput> => {
  return b.MonthThreeFourMilestone(
    input,
  );
};

/**
 * Executes the "MonthTwoMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "MonthTwoMilestone"
 * with the specified parameters.
 *
 * @param { types.MilestoneInput } input - Input parameter.
 *
 * @returns {Promise<types.MilestoneEnhancementOutput>} A promise that resolves with the result of the action.
 */
export const MonthTwoMilestone = async (
  input: types.MilestoneInput,
): Promise<types.MilestoneEnhancementOutput> => {
  return b.MonthTwoMilestone(
    input,
  );
};

/**
 * Executes the "NewbornWeekMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "NewbornWeekMilestone"
 * with the specified parameters.
 *
 * @param { string } babyName - Input parameter.
 * @param { number } week - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { boolean } firstPregnancy - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } height (optional) - Input parameter.
 * @param { number | null } headCircumference (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { string | null } parentWellness (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.NewbornMilestoneOutput>} A promise that resolves with the result of the action.
 */
export const NewbornWeekMilestone = async (
  babyName: string,
  week: number,
  babySex?: string | null,
  firstPregnancy: boolean,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  height?: number | null,
  headCircumference?: number | null,
  feedingCount24h?: number | null,
  sleepCount24h?: number | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  activitySummary?: string | null,
  parentWellness?: string | null,
  medicalContext?: string | null,
): Promise<types.NewbornMilestoneOutput> => {
  return b.NewbornWeekMilestone(
    babyName,
    week,
    babySex,
    firstPregnancy,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    height,
    headCircumference,
    feedingCount24h,
    sleepCount24h,
    recentChatTopics,
    achievedMilestones,
    activitySummary,
    parentWellness,
    medicalContext,
  );
};

/**
 * Executes the "PersonalizedTasks" BAML action.
 *
 * This server action calls the underlying BAML function "PersonalizedTasks"
 * with the specified parameters.
 *
 * @param { number } babyAgeInDays - Input parameter.
 * @param { number } ppWeek - Input parameter.
 * @param { string } timeOfDay - Input parameter.
 * @param { string } feedingMethod - Input parameter.
 *
 * @returns {Promise<types.PersonalizedTasksOutput>} A promise that resolves with the result of the action.
 */
export const PersonalizedTasks = async (
  babyAgeInDays: number,
  ppWeek: number,
  timeOfDay: string,
  feedingMethod: string,
): Promise<types.PersonalizedTasksOutput> => {
  return b.PersonalizedTasks(
    babyAgeInDays,
    ppWeek,
    timeOfDay,
    feedingMethod,
  );
};

/**
 * Executes the "PostpartumTips" BAML action.
 *
 * This server action calls the underlying BAML function "PostpartumTips"
 * with the specified parameters.
 *
 * @param { types.PostpartumTipsInput } input - Input parameter.
 *
 * @returns {Promise<types.PostpartumTipsOutput>} A promise that resolves with the result of the action.
 */
export const PostpartumTips = async (
  input: types.PostpartumTipsInput,
): Promise<types.PostpartumTipsOutput> => {
  return b.PostpartumTips(
    input,
  );
};

/**
 * Executes the "PregnancyWeekSummary" BAML action.
 *
 * This server action calls the underlying BAML function "PregnancyWeekSummary"
 * with the specified parameters.
 *
 * @param { number } week - Input parameter.
 *
 * @returns {Promise<types.PregnancyWeekSummaryOutput>} A promise that resolves with the result of the action.
 */
export const PregnancyWeekSummary = async (
  week: number,
): Promise<types.PregnancyWeekSummaryOutput> => {
  return b.PregnancyWeekSummary(
    week,
  );
};

/**
 * Executes the "RoleSpecificTips" BAML action.
 *
 * This server action calls the underlying BAML function "RoleSpecificTips"
 * with the specified parameters.
 *
 * @param { string } parentRole - Input parameter.
 * @param { number | null } ppDay (optional) - Input parameter.
 * @param { number } babyAgeInDays - Input parameter.
 * @param { string | null } babyName (optional) - Input parameter.
 * @param { string | null } babySex (optional) - Input parameter.
 * @param { string } topic - Input parameter.
 * @param { number | null } recentSleepHours (optional) - Input parameter.
 * @param { string[] | null } concerns (optional) - Input parameter.
 * @param { string | null } recentChatTopics (optional) - Input parameter.
 * @param { string | null } achievedMilestones (optional) - Input parameter.
 * @param { string | null } activitySummary (optional) - Input parameter.
 * @param { string | null } parentWellness (optional) - Input parameter.
 * @param { string | null } medicalContext (optional) - Input parameter.
 *
 * @returns {Promise<types.RoleSpecificTipsOutput>} A promise that resolves with the result of the action.
 */
export const RoleSpecificTips = async (
  parentRole: string,
  ppDay?: number | null,
  babyAgeInDays: number,
  babyName?: string | null,
  babySex?: string | null,
  topic: string,
  recentSleepHours?: number | null,
  concerns?: string[] | null,
  recentChatTopics?: string | null,
  achievedMilestones?: string | null,
  activitySummary?: string | null,
  parentWellness?: string | null,
  medicalContext?: string | null,
): Promise<types.RoleSpecificTipsOutput> => {
  return b.RoleSpecificTips(
    parentRole,
    ppDay,
    babyAgeInDays,
    babyName,
    babySex,
    topic,
    recentSleepHours,
    concerns,
    recentChatTopics,
    achievedMilestones,
    activitySummary,
    parentWellness,
    medicalContext,
  );
};

/**
 * Executes the "SecondWeekMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "SecondWeekMilestone"
 * with the specified parameters.
 *
 * @param { types.MilestoneInput } input - Input parameter.
 *
 * @returns {Promise<types.MilestoneEnhancementOutput>} A promise that resolves with the result of the action.
 */
export const SecondWeekMilestone = async (
  input: types.MilestoneInput,
): Promise<types.MilestoneEnhancementOutput> => {
  return b.SecondWeekMilestone(
    input,
  );
};

/**
 * Executes the "SleepRegressionTips" BAML action.
 *
 * This server action calls the underlying BAML function "SleepRegressionTips"
 * with the specified parameters.
 *
 * @param { string } babyName - Input parameter.
 * @param { number } week - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { number | null } currentWeightOz (optional) - Input parameter.
 * @param { number | null } birthWeightOz (optional) - Input parameter.
 * @param { number | null } sleepCount24h (optional) - Input parameter.
 * @param { number | null } totalSleepHours24h (optional) - Input parameter.
 * @param { number | null } avgSleepHoursPerDay (optional) - Input parameter.
 * @param { number | null } feedingCount24h (optional) - Input parameter.
 *
 * @returns {Promise<types.SleepRegressionTipsOutput>} A promise that resolves with the result of the action.
 */
export const SleepRegressionTips = async (
  babyName: string,
  week: number,
  ageInDays: number,
  currentWeightOz?: number | null,
  birthWeightOz?: number | null,
  sleepCount24h?: number | null,
  totalSleepHours24h?: number | null,
  avgSleepHoursPerDay?: number | null,
  feedingCount24h?: number | null,
): Promise<types.SleepRegressionTipsOutput> => {
  return b.SleepRegressionTips(
    babyName,
    week,
    ageInDays,
    currentWeightOz,
    birthWeightOz,
    sleepCount24h,
    totalSleepHours24h,
    avgSleepHoursPerDay,
    feedingCount24h,
  );
};

/**
 * Executes the "StalePrompts" BAML action.
 *
 * This server action calls the underlying BAML function "StalePrompts"
 * with the specified parameters.
 *
 * @param { string } topic - Input parameter.
 * @param { Record<string, string> } context - Input parameter.
 *
 * @returns {Promise<types.StalePromptsOutput>} A promise that resolves with the result of the action.
 */
export const StalePrompts = async (
  topic: string,
  context: Record<string, string>,
): Promise<types.StalePromptsOutput> => {
  return b.StalePrompts(
    topic,
    context,
  );
};

/**
 * Executes the "SuggestImprovements" BAML action.
 *
 * This server action calls the underlying BAML function "SuggestImprovements"
 * with the specified parameters.
 *
 * @param { string } seo - Input parameter.
 * @param { string } accessibility - Input parameter.
 * @param { string } structure - Input parameter.
 *
 * @returns {Promise<types.ImprovementSuggestions>} A promise that resolves with the result of the action.
 */
export const SuggestImprovements = async (
  seo: string,
  accessibility: string,
  structure: string,
): Promise<types.ImprovementSuggestions> => {
  return b.SuggestImprovements(
    seo,
    accessibility,
    structure,
  );
};

/**
 * Executes the "ThirdWeekMilestone" BAML action.
 *
 * This server action calls the underlying BAML function "ThirdWeekMilestone"
 * with the specified parameters.
 *
 * @param { types.MilestoneInput } input - Input parameter.
 *
 * @returns {Promise<types.MilestoneEnhancementOutput>} A promise that resolves with the result of the action.
 */
export const ThirdWeekMilestone = async (
  input: types.MilestoneInput,
): Promise<types.MilestoneEnhancementOutput> => {
  return b.ThirdWeekMilestone(
    input,
  );
};

/**
 * Executes the "WellnessScreening" BAML action.
 *
 * This server action calls the underlying BAML function "WellnessScreening"
 * with the specified parameters.
 *
 * @param { number } ppDay - Input parameter.
 * @param { number | null } ppWeek (optional) - Input parameter.
 * @param { boolean } firstPregnancy - Input parameter.
 * @param { string } babyFirstName - Input parameter.
 * @param { number } ageInDays - Input parameter.
 * @param { string } previousCheckIns - Input parameter.
 *
 * @returns {Promise<types.WellnessScreeningOutput>} A promise that resolves with the result of the action.
 */
export const WellnessScreening = async (
  ppDay: number,
  ppWeek?: number | null,
  firstPregnancy: boolean,
  babyFirstName: string,
  ageInDays: number,
  previousCheckIns: string,
): Promise<types.WellnessScreeningOutput> => {
  return b.WellnessScreening(
    ppDay,
    ppWeek,
    firstPregnancy,
    babyFirstName,
    ageInDays,
    previousCheckIns,
  );
};