/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  AppointmentNudgeOutput,  BabyAssistantChatOutput,  BabyContext,  BabyVisitExplainerOutput,  BirthPlanHeadlineOutput,  CelebrationQuestion,  CelebrationQuestionsOutput,  CelebrationStatistics,  CelebrationSummaryOutput,  ChatMessage,  ChatTitleOutput,  CheckInQuestion,  ContextualMilestonesOutput,  DailyCheckInQuestionsOutput,  DailyLearningPlan,  DoctorQuestionsOutput,  HospitalPackAdviceOutput,  ImprovementSuggestions,  LearningPlanItem,  LearningTip,  MilestoneEnhancementOutput,  MilestoneExplanationOutput,  MilestoneInput,  MilestonePlan,  MilestonePlanItem,  MilestoneSuggestion,  NewbornMilestoneOutput,  ParentTask,  ParentTip,  PersonalizedTasksOutput,  PostpartumTipsInput,  PostpartumTipsOutput,  PregnancyWeekSummaryOutput,  ResponseType,  RoleSpecificTipsOutput,  SleepRegressionTipsOutput,  StalePromptsOutput,  WellnessQuestion,  WellnessScreeningOutput } from "../types"

import type * as types from "../types"
import type { partial_types }from "../partial_types";

export type StreamingServerTypes = {
  AppointmentNudge: AppointmentNudgeOutput,
  BabyAssistantChat: BabyAssistantChatOutput,
  BabyVisitExplainer: BabyVisitExplainerOutput,
  BirthPlanHeadline: BirthPlanHeadlineOutput,
  DailyCheckInQuestions: DailyCheckInQuestionsOutput,
  DailyLearningPlanner: DailyLearningPlan,
  EnhanceMilestone: MilestoneEnhancementOutput,
  FirstWeekMilestone: MilestoneEnhancementOutput,
  GenerateCelebrationSummary: CelebrationSummaryOutput,
  GenerateChatTitle: ChatTitleOutput,
  GenerateContextualMilestones: ContextualMilestonesOutput,
  GenerateDoctorQuestions: DoctorQuestionsOutput,
  GenerateLearningTip_FirstWeek: LearningTip,
  GenerateLearningTip_ImmediatePostbirth: LearningTip,
  GenerateLearningTip_MonthOne: LearningTip,
  GenerateLearningTip_MonthThreeFour: LearningTip,
  GenerateLearningTip_MonthTwo: LearningTip,
  GenerateLearningTip_SecondWeek: LearningTip,
  GenerateLearningTip_ThirdWeek: LearningTip,
  HospitalPackAdvice: HospitalPackAdviceOutput,
  ImmediatePostbirthMilestone: MilestoneEnhancementOutput,
  MilestoneExplanation: MilestoneExplanationOutput,
  MilestonePlanner: MilestonePlan,
  MonthOneMilestone: MilestoneEnhancementOutput,
  MonthThreeFourMilestone: MilestoneEnhancementOutput,
  MonthTwoMilestone: MilestoneEnhancementOutput,
  NewbornWeekMilestone: NewbornMilestoneOutput,
  PersonalizedTasks: PersonalizedTasksOutput,
  PlanCelebrationQuestions: CelebrationQuestionsOutput,
  PostpartumTips: PostpartumTipsOutput,
  PregnancyWeekSummary: PregnancyWeekSummaryOutput,
  RoleSpecificTips: RoleSpecificTipsOutput,
  SecondWeekMilestone: MilestoneEnhancementOutput,
  SleepRegressionTips: SleepRegressionTipsOutput,
  StalePrompts: StalePromptsOutput,
  SuggestImprovements: ImprovementSuggestions,
  ThirdWeekMilestone: MilestoneEnhancementOutput,
  WellnessScreening: WellnessScreeningOutput,
}